# Generated by Django 6.0 on 2026-01-08 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(help_text='Insira a data e horário do registro da OS.', verbose_name='Data e Horário do Registro')),
                ('protocolo', models.CharField(error_messages={'blank': 'O campo não pode estar vazio. Por favor, insira o protocolo da OS.', 'max_length': 'O protocolo excedeu o número máximo de caracteres permitidos (20).', 'null': 'O campo não pode ser nulo. Por favor, insira o protocolo da OS.', 'unique': 'Este protocolo já existe. Por favor, verifique e tente novamente.'}, help_text='Digite o protocolo da OS, ex: 123456789...', max_length=20, unique=True, verbose_name='Protocolo')),
                ('elevador', models.IntegerField(choices=[(1, 'Social 1 - M2674'), (2, 'Social 2 - M2675'), (3, 'Social 3 - M2676'), (4, 'Social 4 - M2677'), (5, 'Social 5 - M2678'), (6, 'Serviço 6 - M2679'), (7, 'Social 7 - M2680'), (8, 'Social 8 - M2681'), (9, 'Social 9 - M2682'), (10, 'Social 10 - M2683'), (11, 'Social 11 - M2684'), (12, 'Social 12 - M2685'), (13, 'Social 13 - M2686'), (14, 'Serviço 14 - M2687')], help_text='Selecione o elevador relacionado à OS.', verbose_name='Elevador')),
                ('aprisionamento', models.BooleanField(blank=True, default=None, null=True, verbose_name='Aprisionamento')),
                ('ocorrencia', models.CharField(blank=True, help_text='Descreva a ocorrência relacionada à OS.', max_length=600, verbose_name='Ocorrência')),
                ('atendente', models.CharField(default='', max_length=200, verbose_name='Atendente')),
                ('solicitante', models.CharField(default='', max_length=200, verbose_name='Solicitante')),
                ('elevador_parado', models.IntegerField(choices=[(1, 'Ativo'), (2, 'Parado')], default=1, verbose_name='Status do Elevador')),
                ('status', models.CharField(default='ABERTA', max_length=20, null=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CloseOs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_chegada', models.DateTimeField(help_text='Insira a data e horário de chegada ao local.', verbose_name='Data e Horário de Chegada')),
                ('data_hora_saida', models.DateTimeField(help_text='Insira a data e horário de saída do local.', verbose_name='Data e Horário de Saída')),
                ('tecnico', models.CharField(default='', help_text='Insira o nome do técnico responsável pelo atendimento.', max_length=200, verbose_name='Técnico Responsável')),
                ('servico', models.CharField(blank=True, default='', help_text='Descreva a solução aplicada na OS.', max_length=600, verbose_name='Serviço Executado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('protocolo', models.OneToOneField(limit_choices_to={'status': 'ABERTA'}, on_delete=django.db.models.deletion.CASCADE, to='service_orders.serviceorder', verbose_name='Protocolo')),
            ],
        ),
    ]
