# Generated by Django 6.0 on 2025-12-19 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseOs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_chegada', models.DateTimeField(auto_now=True, help_text='Insira a data e horário de chegada ao local.', verbose_name='Data e Horário de Chegada')),
                ('data_hora_saida', models.DateTimeField(auto_now=True, help_text='Insira a data e horário de saída do local.', verbose_name='Data e Horário de Saída')),
                ('servico', models.CharField(blank=True, help_text='Descreva a solução aplicada na OS.', max_length=600, verbose_name='Serviço Executado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('protocolo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service_orders.serviceorder')),
            ],
        ),
    ]
