# Generated by Django 6.0 on 2026-01-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='elevador',
            field=models.CharField(choices=[('1', 'Social 1 - M2674'), ('2', 'Social 2 - M2675'), ('3', 'Social 3 - M2676'), ('4', 'Social 4 - M2677'), ('5', 'Social 5 - M2678'), ('6', 'Serviço 6 - M2679'), ('7', 'Social 7 - M2680'), ('8', 'Social 8 - M2681'), ('9', 'Social 9 - M2682'), ('10', 'Social 10 - M2683'), ('11', 'Social 11 - M2684'), ('12', 'Social 12 - M2685'), ('13', 'Social 13 - M2686'), ('14', 'Serviço 14 - M2687')], help_text='Selecione o elevador relacionado à OS.', max_length=50, verbose_name='Elevador'),
        ),
    ]
