# Generated by Django 6.0 on 2026-01-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0002_alter_serviceorder_elevador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='elevador_parado',
            field=models.CharField(choices=[(1, 'Ativo'), (2, 'Parado')], default='1', max_length=10, verbose_name='Status do Elevador'),
        ),
    ]
