# Generated by Django 6.0 on 2025-12-19 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0002_closeos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceorder',
            old_name='status_elevador',
            new_name='elevador_parado',
        ),
        migrations.AddField(
            model_name='closeos',
            name='tecnico',
            field=models.CharField(default='', help_text='Insira o nome do técnico responsável pelo atendimento.', max_length=200, verbose_name='Técnico Responsável'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(default='ABERTA', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='closeos',
            name='protocolo',
            field=models.OneToOneField(limit_choices_to={'status': 'ABERTA'}, on_delete=django.db.models.deletion.CASCADE, to='service_orders.serviceorder', verbose_name='Protocolo'),
        ),
        migrations.AlterField(
            model_name='closeos',
            name='servico',
            field=models.CharField(blank=True, default='', help_text='Descreva a solução aplicada na OS.', max_length=600, verbose_name='Serviço Executado'),
        ),
    ]
