# Generated by Django 6.0 on 2026-01-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0005_alter_serviceorder_elevador_parado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='elevador_parado',
            field=models.CharField(choices=[('1', 'Ativo'), ('2', 'Parado')], default='Ativo', max_length=10, null=True, verbose_name='Status do Elevador'),
        ),
    ]
