# Generated by Django 6.0 on 2026-01-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0006_alter_serviceorder_elevador_parado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngServiceReg',
            fields=[
                ('os_id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
                ('servico', models.CharField(choices=[('1', 'Água e Esgoto'), ('2', 'Ar Condicionado'), ('3', 'Arquitetura e Projetos'), ('4', 'Áudio & Vídeo'), ('5', 'Carregadores'), ('6', 'Copa'), ('7', 'Eletrodomésticos e Equip. Eletrônicos'), ('8', 'Elevadores'), ('9', 'Energia Elétrica'), ('10', 'Limpeza'), ('11', 'Manutenção Geradores - Corretivas'), ('12', 'Manutenção Preditiva'), ('13', 'Marcenaria'), ('14', 'Obras'), ('15', 'Outros Serviços de Manutenção Predial'), ('16', 'Serralheria'), ('17', 'Obras'), ('18', 'Chaveiro'), ('19', 'Telefonia')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='CloseOs',
            new_name='ElevOrderClose',
        ),
        migrations.RenameModel(
            old_name='ServiceOrder',
            new_name='ElevOrderReg',
        ),
    ]
