# Generated by Django 6.0 on 2026-01-16 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0007_engservicereg_rename_closeos_elevorderclose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='elevorderreg',
            name='data_hora_chegada',
            field=models.DateTimeField(blank=True, help_text='Insira a data e horário de chegada ao local.', null=True, verbose_name='Data e Horário de Chegada'),
        ),
        migrations.AddField(
            model_name='elevorderreg',
            name='data_hora_saida',
            field=models.DateTimeField(blank=True, help_text='Insira a data e horário de saída do local.', null=True, verbose_name='Data e Horário de Saída'),
        ),
        migrations.AddField(
            model_name='elevorderreg',
            name='servico',
            field=models.CharField(blank=True, default='', help_text='Descreva a solução aplicada na OS.', max_length=600, verbose_name='Serviço Executado'),
        ),
        migrations.AddField(
            model_name='elevorderreg',
            name='tecnico',
            field=models.CharField(default='', help_text='Insira o nome do técnico responsável pelo atendimento.', max_length=200, verbose_name='Técnico Responsável'),
        ),
        migrations.AddField(
            model_name='engservicereg',
            name='data_hora_atendimento',
            field=models.DateTimeField(blank=True, help_text='Insira a data e horário de conclusão da OS.', null=True, verbose_name='Data e Horário de Fechamento'),
        ),
        migrations.AddField(
            model_name='engservicereg',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engservicereg',
            name='local',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='engservicereg',
            name='supervisor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='engservicereg',
            name='tecnico_responsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='engservicereg',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_da_categoria', to='service_orders.categoria'),
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao_padrao', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='service_orders.categoria')),
            ],
        ),
        migrations.AlterField(
            model_name='engservicereg',
            name='servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_do_servico', to='service_orders.servico'),
        ),
    ]
