# Generated by Django 6.0 on 2026-01-19 15:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0008_categoria_elevorderreg_data_hora_chegada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='descricao_padrao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
