# Generated by Django 6.0 on 2026-01-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0009_categoria_created_at_categoria_descricao_padrao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='descricao_padrao',
            new_name='descricao_categoria',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='nome',
            new_name='nome_categoria',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='descricao_padrao',
            new_name='descricao_servico',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='nome',
            new_name='nome_servico',
        ),
    ]
