# Generated by Django 6.0 on 2026-01-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0010_rename_descricao_padrao_categoria_descricao_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='nome_servico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
