# Generated by Django 6.0 on 2026-01-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0011_alter_servico_nome_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descricao_categoria',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome_categoria',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao_servico',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome_servico',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
