# Generated by Django 6.0 on 2026-01-29 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_contratosvigentes_delete_contratos'),
        ('service_orders', '0012_alter_categoria_descricao_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engservicereg',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='contratos.contratosvigentes'),
        ),
        migrations.AddField(
            model_name='engservicereg',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_os', to='contratos.contratosvigentes'),
        ),
        migrations.AlterField(
            model_name='elevorderreg',
            name='elevador',
            field=models.CharField(choices=[('Social 1 - M2674', 'Social 1 - M2674'), ('Social 2 - M2675', 'Social 2 - M2675'), ('Social 3 - M2676', 'Social 3 - M2676'), ('Social 4 - M2677', 'Social 4 - M2677'), ('Social 5 - M2678', 'Social 5 - M2678'), ('Serviço 6 - M2679', 'Serviço 6 - M2679'), ('Social 7 - M2680', 'Social 7 - M2680'), ('Social 8 - M2681', 'Social 8 - M2681'), ('Social 9 - M2682', 'Social 9 - M2682'), ('Social 10 - M2683', 'Social 10 - M2683'), ('Social 11 - M2684', 'Social 11 - M2684'), ('Social 12 - M2685', 'Social 12 - M2685'), ('Social 13 - M2686', 'Social 13 - M2686'), ('Serviço 14 - M2687', 'Serviço 14 - M2687')], help_text='Selecione o elevador relacionado à OS.', max_length=50, verbose_name='Elevador'),
        ),
        migrations.DeleteModel(
            name='ElevOrderClose',
        ),
    ]
