# Generated by Django 6.0 on 2026-04-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0013_engservicereg_contrato_engservicereg_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevorderreg',
            name='elevador',
            field=models.CharField(choices=[('Social 1 - M2674', 'Social 1 - M2674'), ('Social 2 - M2675', 'Social 2 - M2675'), ('Social 3 - M2676', 'Social 3 - M2676'), ('Social 4 - M2677', 'Social 4 - M2677'), ('Social 5 - M2678', 'Social 5 - M2678'), ('Serviço 6 - M2679', 'Serviço 6 - M2679'), ('Privativo 7 - M2680', 'Privativo 7 - M2680'), ('Social 8 - M2681', 'Social 8 - M2681'), ('Social 9 - M2682', 'Social 9 - M2682'), ('Privativo 10 - M2683', 'Privativo 10 - M2683'), ('Social 11 - M2684', 'Social 11 - M2684'), ('Social 12 - M2685', 'Social 12 - M2685'), ('Social 13 - M2686', 'Social 13 - M2686'), ('Serviço 14 - M2687', 'Serviço 14 - M2687')], help_text='Selecione o elevador relacionado à OS.', max_length=50, verbose_name='Elevador'),
        ),
        migrations.AlterField(
            model_name='elevorderreg',
            name='elevador_parado',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('PARADO', 'Parado')], default='Ativo', max_length=10, null=True, verbose_name='Status do Elevador'),
        ),
        migrations.AlterField(
            model_name='elevorderreg',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'ABERTA'), ('CONCLUIDA', 'CONCLUIDA')], default='Ativo', max_length=20, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
