# Generated by Django 6.0 on 2026-04-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0014_alter_elevorderreg_elevador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevorderreg',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'ABERTA'), ('CONCLUIDA', 'CONCLUIDA')], default='ABERTA', max_length=20, verbose_name='Status'),
        ),
    ]
