# Generated by Django 6.0 on 2026-05-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0015_alter_elevorderreg_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevorderreg',
            name='tempo_parado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Horas Úteis Parado'),
        ),
    ]
