# Generated by Django 6.0 on 2026-05-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0016_elevorderreg_tempo_parado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevorderreg',
            name='data_hora_saida',
        ),
        migrations.AddField(
            model_name='elevorderreg',
            name='data_hora_conclusao',
            field=models.DateTimeField(blank=True, help_text='Insira a data e horário de Conclusão.', null=True, verbose_name='Data e Horário de Conclusão'),
        ),
    ]
