# Generated by Django 6.0 on 2026-05-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0017_remove_elevorderreg_data_hora_saida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevorderreg',
            name='elevador_parado',
            field=models.CharField(choices=[('ATIVO', 'ATIVO'), ('PARADO', 'PARADO')], max_length=10, null=True, verbose_name='Status do Elevador'),
        ),
    ]
