# Generated by Django 6.0 on 2026-05-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0018_alter_elevorderreg_elevador_parado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevorderreg',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'ABERTA'), ('CONCLUIDA', 'CONCLUIDA')], max_length=20, verbose_name='Status'),
        ),
    ]
