# Generated by Django 6.0 on 2026-07-06 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServidorReembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do servidor', max_length=200)),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('cargo', models.CharField(help_text='Ex: Assessor-Chefe, CJ-3', max_length=150)),
                ('portaria_designacao', models.CharField(blank=True, help_text='Ex: Portaria 380, de 28 de agosto de 2025', max_length=200, null=True)),
                ('banco', models.CharField(help_text='Ex: Banco do Brasil', max_length=100)),
                ('agencia', models.CharField(max_length=50)),
                ('conta_corrente', models.CharField(max_length=50)),
                ('telefone_linha', models.CharField(help_text='Linha Telefônica Utilizada (ex: 61 99943-9030)', max_length=20)),
                ('teto_ressarcimento', models.DecimalField(decimal_places=2, default=330.0, help_text='Valor máximo de ressarcimento mensal (Art. 1º IN 10/2014)', max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoReembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField(help_text='Data de início do período da fatura')),
                ('periodo_fim', models.DateField(help_text='Data de fim do período da fatura')),
                ('valor_fatura', models.DecimalField(decimal_places=2, help_text='Valor Total da Fatura', max_digits=10)),
                ('valor_servico', models.DecimalField(decimal_places=2, help_text='Valor Utilizado a Serviço', max_digits=10)),
                ('valor_ressarcido', models.DecimalField(blank=True, decimal_places=2, help_text='Valor a ser Ressarcido (Calculado)', max_digits=10, null=True)),
                ('fatura_anexa', models.CharField(blank=True, help_text='Número SEI da Fatura ou link', max_length=200, null=True)),
                ('comprovante_pagamento', models.CharField(blank=True, help_text='Número SEI do Comprovante', max_length=200, null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Informações Complementares', null=True)),
                ('status', models.CharField(choices=[('em_analise', 'Em Análise'), ('aprovada', 'Aprovada'), ('negada', 'Negada')], default='em_analise', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='reembolsos.servidorreembolso')),
            ],
        ),
    ]
