# Generated by Django 6.0 on 2026-07-06 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reembolsos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteReembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.IntegerField(unique=True)),
                ('cargo', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='servidorreembolso',
            name='cargo',
            field=models.CharField(blank=True, help_text='Ex: Assessor-Chefe, CJ-3', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='servidorreembolso',
            name='cargo_limite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servidores', to='reembolsos.limitereembolso'),
        ),
    ]
