# Generated by Django 6.0 on 2026-07-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reembolsos', '0002_limitereembolso_alter_servidorreembolso_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidorreembolso',
            name='nota_designacao',
            field=models.TextField(blank=True, help_text='Texto completo da Nota de Designação para o PDF', null=True),
        ),
        migrations.AddField(
            model_name='servidorreembolso',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações adicionais para o PDF', null=True),
        ),
    ]
