# Generated by Django 6.0 on 2026-07-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reembolsos', '0003_servidorreembolso_nota_designacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoreembolso',
            name='protocolo_sei',
            field=models.CharField(blank=True, help_text='Protocolo SEI da Solicitação', max_length=50, null=True),
        ),
    ]
