# Generated by Django 6.0 on 2026-07-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reembolsos', '0004_solicitacaoreembolso_protocolo_sei'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidorreembolso',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se o servidor está ativo para receber reembolsos'),
        ),
    ]
