# Generated by Django 6.0 on 2026-07-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reembolsos', '0005_servidorreembolso_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoreembolso',
            name='data_pagamento',
            field=models.DateField(blank=True, help_text='Data do Pagamento', null=True),
        ),
        migrations.AddField(
            model_name='solicitacaoreembolso',
            name='protocolo_ordem_bancaria',
            field=models.CharField(blank=True, help_text='Protocolo SEI da Ordem Bancária de Pagamento', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacaoreembolso',
            name='status',
            field=models.CharField(choices=[('em_analise', 'Em Análise'), ('pendente', 'Pendente'), ('enviado', 'Enviado'), ('aprovada', 'Aprovada'), ('concluido', 'Concluído'), ('negada', 'Negada')], default='em_analise', max_length=20),
        ),
    ]
