# Generated by Django 6.0 on 2026-07-08 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reembolsos', '0006_solicitacaoreembolso_data_pagamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaoreembolso',
            name='comprovante_pagamento',
        ),
        migrations.RemoveField(
            model_name='solicitacaoreembolso',
            name='fatura_anexa',
        ),
        migrations.RemoveField(
            model_name='solicitacaoreembolso',
            name='periodo_fim',
        ),
        migrations.RemoveField(
            model_name='solicitacaoreembolso',
            name='periodo_inicio',
        ),
        migrations.RemoveField(
            model_name='solicitacaoreembolso',
            name='valor_fatura',
        ),
        migrations.RemoveField(
            model_name='solicitacaoreembolso',
            name='valor_ressarcido',
        ),
        migrations.RemoveField(
            model_name='solicitacaoreembolso',
            name='valor_servico',
        ),
        migrations.CreateModel(
            name='FaturaReembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField(blank=True, help_text='Data de início do período da fatura', null=True)),
                ('periodo_fim', models.DateField(blank=True, help_text='Data de fim do período da fatura', null=True)),
                ('valor_fatura', models.DecimalField(blank=True, decimal_places=2, help_text='Valor Total da Fatura', max_digits=10, null=True)),
                ('valor_servico', models.DecimalField(blank=True, decimal_places=2, help_text='Valor Utilizado a Serviço', max_digits=10, null=True)),
                ('valor_ressarcido', models.DecimalField(blank=True, decimal_places=2, help_text='Valor a ser Ressarcido (Calculado)', max_digits=10, null=True)),
                ('fatura_anexa', models.CharField(blank=True, help_text='Número SEI da Fatura ou link', max_length=200, null=True)),
                ('comprovante_pagamento', models.CharField(blank=True, help_text='Número SEI do Comprovante', max_length=200, null=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='reembolsos.solicitacaoreembolso')),
            ],
        ),
    ]
