# Generated by Django 6.0 on 2026-07-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reembolsos', '0007_remove_solicitacaoreembolso_comprovante_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidorreembolso',
            name='data_publicacao_portaria',
            field=models.DateField(blank=True, help_text='Data de publicação da portaria', null=True),
        ),
    ]
