# Generated by Django 6.0 on 2026-07-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reembolsos', '0008_servidorreembolso_data_publicacao_portaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabecalho_linha1', models.CharField(default='Tribunal Superior Eleitoral', help_text='Primeira linha do cabeçalho', max_length=200)),
                ('cabecalho_linha2', models.CharField(default='Secretaria de Administração', help_text='Segunda linha do cabeçalho', max_length=200)),
                ('cabecalho_linha3', models.CharField(default='Seção de Equipamentos e Sistemas de Engenharia', help_text='Terceira linha do cabeçalho', max_length=200)),
                ('titulo_tabela_anual', models.CharField(default='CONTROLE DOS VALORES GASTOS ANUALMENTE COM TELEFONIA MÓVEL - Nº 11 DE 2022', help_text='Título exibido acima da tabela principal', max_length=255)),
                ('nota_rodape_1', models.TextField(default='<b>(*)</b> Para fins de apuração do período em que se deu os gastos com telefonia móvel, utilizar-se-á o Regime de Competência. Este Regime tem os valores contabilizados dentro do mês onde se iniciou o fato Gerador.<br/><br/><b>(**)</b> Na Instrução Normativa TSE nº 11/2022 - Anexo I está a tabela referencial de valores máximos a serem custeados pelo Tribunal.', help_text='Texto da primeira nota de rodapé')),
                ('nota_rodape_2_prefix', models.CharField(default='<b>Nota de Designação:</b>', help_text='Prefixo da nota de designação', max_length=100)),
            ],
        ),
    ]
