# Generated by Django 6.0 on 2026-07-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reembolsos', '0009_configuracaorelatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidorreembolso',
            name='protocolo_autorizacao',
            field=models.CharField(blank=True, help_text='Protocolo SEI de autorização, caso exigido', max_length=50, null=True),
        ),
    ]
