# Generated by Django 6.0 on 2026-07-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reembolsos', '0010_servidorreembolso_protocolo_autorizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturareembolso',
            name='aprovada',
            field=models.BooleanField(default=True, help_text='Indica se esta fatura específica foi aprovada'),
        ),
        migrations.AddField(
            model_name='faturareembolso',
            name='justificativa_negacao',
            field=models.TextField(blank=True, help_text='Justificativa caso a fatura seja negada', null=True),
        ),
    ]
