# Generated by Django 6.0 on 2026-07-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reembolsos', '0011_faturareembolso_aprovada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidorreembolso',
            name='nota_autorizacao',
            field=models.TextField(blank=True, help_text='Texto completo da Nota de Autorização para o PDF', null=True),
        ),
    ]
