# Generated by Django 5.2.8 on 2026-07-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reembolsos', '0012_servidorreembolso_nota_autorizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaorelatorio',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='faturareembolso',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='limitereembolso',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servidorreembolso',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='solicitacaoreembolso',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
