# Generated by Django 5.2.8 on 2026-07-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reembolsos', '0014_alter_configuracaorelatorio_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitereembolso',
            name='requer_autorizacao',
            field=models.BooleanField(default=False, help_text='Se marcado, exibirá os campos de autorização no formulário.'),
        ),
        migrations.AddField(
            model_name='servidorreembolso',
            name='inicio_validade_autorizacao',
            field=models.DateField(blank=True, help_text='Data de início da validade da autorização', null=True),
        ),
        migrations.AlterField(
            model_name='configuracaorelatorio',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='faturareembolso',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='limitereembolso',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servidorreembolso',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='solicitacaoreembolso',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
