# Generated by Django 5.2.8 on 2026-07-28 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reembolsos', '0017_servidorreembolso_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidorreembolso',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='servidorreembolso',
            name='nome',
        ),
    ]
