# Generated by Django 6.0 on 2026-07-08 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaPatrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('numero_requisicao', models.CharField(blank=True, help_text='Número da requisição no sistema corporativo', max_length=50, null=True)),
                ('origem', models.CharField(help_text='Local de origem', max_length=200)),
                ('destino', models.CharField(help_text='Local de destino', max_length=200)),
                ('data_transferencia', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.CharField(help_text='Pessoa responsável pela transferência', max_length=150)),
                ('motivo', models.TextField(blank=True, help_text='Motivo da transferência', null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
