# Generated by Django 6.0 on 2026-05-18 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(blank=True, default='', max_length=100)),
                ('descricao_categoria', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElevOrderReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(help_text='Insira a data e horário do registro da OS.', verbose_name='Data e Horário do Registro')),
                ('protocolo', models.CharField(error_messages={'blank': 'O campo não pode estar vazio. Por favor, insira o protocolo da OS.', 'max_length': 'O protocolo excedeu o número máximo de caracteres permitidos (20).', 'null': 'O campo não pode ser nulo. Por favor, insira o protocolo da OS.', 'unique': 'Este protocolo já existe. Por favor, verifique e tente novamente.'}, help_text='Digite o protocolo da OS, ex: 123456789...', max_length=20, unique=True, verbose_name='Protocolo')),
                ('elevador', models.CharField(choices=[('Social 1 - M2674', 'Social 1 - M2674'), ('Social 2 - M2675', 'Social 2 - M2675'), ('Social 3 - M2676', 'Social 3 - M2676'), ('Social 4 - M2677', 'Social 4 - M2677'), ('Social 5 - M2678', 'Social 5 - M2678'), ('Serviço 6 - M2679', 'Serviço 6 - M2679'), ('Privativo 7 - M2680', 'Privativo 7 - M2680'), ('Social 8 - M2681', 'Social 8 - M2681'), ('Social 9 - M2682', 'Social 9 - M2682'), ('Privativo 10 - M2683', 'Privativo 10 - M2683'), ('Social 11 - M2684', 'Social 11 - M2684'), ('Social 12 - M2685', 'Social 12 - M2685'), ('Social 13 - M2686', 'Social 13 - M2686'), ('Serviço 14 - M2687', 'Serviço 14 - M2687')], help_text='Selecione o elevador relacionado à OS.', max_length=50, verbose_name='Elevador')),
                ('aprisionamento', models.BooleanField(blank=True, default=None, null=True, verbose_name='Aprisionamento')),
                ('ocorrencia', models.CharField(blank=True, help_text='Descreva a ocorrência relacionada à OS.', max_length=600, verbose_name='Ocorrência')),
                ('atendente', models.CharField(default='', max_length=200, verbose_name='Atendente')),
                ('solicitante', models.CharField(default='', max_length=200, verbose_name='Solicitante')),
                ('elevador_parado', models.CharField(choices=[('ATIVO', 'ATIVO'), ('PARADO', 'PARADO')], max_length=10, null=True, verbose_name='Status do Elevador')),
                ('data_hora_chegada', models.DateTimeField(blank=True, help_text='Insira a data e horário de chegada ao local.', null=True, verbose_name='Data e Horário de Chegada')),
                ('data_hora_conclusao', models.DateTimeField(blank=True, help_text='Insira a data e horário de Conclusão.', null=True, verbose_name='Data e Horário de Conclusão')),
                ('tempo_parado', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Horas Úteis Parado')),
                ('tecnico', models.CharField(default='', help_text='Insira o nome do técnico responsável pelo atendimento.', max_length=200, verbose_name='Técnico Responsável')),
                ('servico', models.CharField(blank=True, default='', help_text='Descreva a solução aplicada na OS.', max_length=600, verbose_name='Serviço Executado')),
                ('status', models.CharField(choices=[('ABERTA', 'ABERTA'), ('CONCLUIDA', 'CONCLUIDA')], max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(blank=True, default='', max_length=100)),
                ('descricao_servico', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='elevadores.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='EngServiceReg',
            fields=[
                ('os_id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=15, null=True)),
                ('data_hora_atendimento', models.DateTimeField(blank=True, help_text='Insira a data e horário de conclusão da OS.', null=True, verbose_name='Data e Horário de Fechamento')),
                ('supervisor', models.CharField(blank=True, max_length=100, null=True)),
                ('tecnico_responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_da_categoria', to='elevadores.categoria')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='contratos.contratos')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_os', to='contratos.contratos')),
                ('servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_do_servico', to='elevadores.servico')),
            ],
        ),
    ]
