# Generated by Django 6.0 on 2026-07-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevorderreg',
            name='tipo_chamado',
            field=models.CharField(choices=[('CORRETIVO', 'CORRETIVO'), ('PREVENTIVO', 'PREVENTIVO'), ('EMERGENCIAL', 'EMERGENCIAL')], default='CORRETIVO', max_length=20, verbose_name='Tipo de Chamado'),
        ),
    ]
