# Generated by Django 6.0 on 2026-07-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevadores', '0002_elevorderreg_tipo_chamado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevadorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevador', models.CharField(choices=[('Social 1 - M2674', 'Social 1 - M2674'), ('Social 2 - M2675', 'Social 2 - M2675'), ('Social 3 - M2676', 'Social 3 - M2676'), ('Social 4 - M2677', 'Social 4 - M2677'), ('Social 5 - M2678', 'Social 5 - M2678'), ('Serviço 6 - M2679', 'Serviço 6 - M2679'), ('Privativo 7 - M2680', 'Privativo 7 - M2680'), ('Social 8 - M2681', 'Social 8 - M2681'), ('Social 9 - M2682', 'Social 9 - M2682'), ('Privativo 10 - M2683', 'Privativo 10 - M2683'), ('Social 11 - M2684', 'Social 11 - M2684'), ('Social 12 - M2685', 'Social 12 - M2685'), ('Social 13 - M2686', 'Social 13 - M2686'), ('Serviço 14 - M2687', 'Serviço 14 - M2687')], max_length=50, unique=True, verbose_name='Elevador')),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('PARADO', 'PARADO')], default='ATIVO', max_length=10, verbose_name='Status Atual')),
                ('data_hora_parada', models.DateTimeField(blank=True, help_text='Data e hora em que o elevador ficou inoperante.', null=True, verbose_name='Parado Desde')),
            ],
        ),
    ]
