# Generated by Django 6.0 on 2026-07-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevadores', '0003_elevadorstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManutencaoPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevador', models.CharField(choices=[('Social 1 - M2674', 'Social 1 - M2674'), ('Social 2 - M2675', 'Social 2 - M2675'), ('Social 3 - M2676', 'Social 3 - M2676'), ('Social 4 - M2677', 'Social 4 - M2677'), ('Social 5 - M2678', 'Social 5 - M2678'), ('Serviço 6 - M2679', 'Serviço 6 - M2679'), ('Privativo 7 - M2680', 'Privativo 7 - M2680'), ('Social 8 - M2681', 'Social 8 - M2681'), ('Social 9 - M2682', 'Social 9 - M2682'), ('Privativo 10 - M2683', 'Privativo 10 - M2683'), ('Social 11 - M2684', 'Social 11 - M2684'), ('Social 12 - M2685', 'Social 12 - M2685'), ('Social 13 - M2686', 'Social 13 - M2686'), ('Serviço 14 - M2687', 'Serviço 14 - M2687')], help_text='Selecione o elevador.', max_length=50, verbose_name='Elevador')),
                ('data_execucao', models.DateField(blank=True, null=True, verbose_name='Data da Execução')),
                ('ordem_servico', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ordem de Serviço')),
                ('tecnico', models.CharField(blank=True, max_length=200, null=True, verbose_name='Executado Por')),
                ('status', models.CharField(choices=[('EXECUTADO', 'Executado'), ('INOPERANTE', 'Inoperante'), ('NAO_EXECUTADO', 'Não Executado')], default='EXECUTADO', max_length=20, verbose_name='Status')),
                ('qtd_chamado', models.IntegerField(blank=True, null=True, verbose_name='Qtd. de Chamados (ICR)')),
                ('icr_atingido', models.CharField(blank=True, help_text='S ou N', max_length=10, null=True, verbose_name='ICR <= 3')),
                ('qhp', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='QHP (Horas de Elevador Parado)')),
                ('qdu', models.IntegerField(blank=True, null=True, verbose_name='QDU (Dias Úteis)')),
                ('ddm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='DDM (%)')),
                ('ddm_atingido', models.CharField(blank=True, help_text='S ou N', max_length=10, null=True, verbose_name='DDM >= 90%')),
                ('mes_referencia', models.DateField(help_text='O mês e ano a qual este relatório pertence (use o dia 1 do mês)', verbose_name='Mês de Referência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
