# Generated by Django 6.0 on 2026-07-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevadores', '0004_manutencaopreventiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='PecaManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevador', models.CharField(choices=[('Social 1 - M2674', 'Social 1 - M2674'), ('Social 2 - M2675', 'Social 2 - M2675'), ('Social 3 - M2676', 'Social 3 - M2676'), ('Social 4 - M2677', 'Social 4 - M2677'), ('Social 5 - M2678', 'Social 5 - M2678'), ('Serviço 6 - M2679', 'Serviço 6 - M2679'), ('Privativo 7 - M2680', 'Privativo 7 - M2680'), ('Social 8 - M2681', 'Social 8 - M2681'), ('Social 9 - M2682', 'Social 9 - M2682'), ('Privativo 10 - M2683', 'Privativo 10 - M2683'), ('Social 11 - M2684', 'Social 11 - M2684'), ('Social 12 - M2685', 'Social 12 - M2685'), ('Social 13 - M2686', 'Social 13 - M2686'), ('Serviço 14 - M2687', 'Serviço 14 - M2687')], max_length=50, verbose_name='Elevador')),
                ('andar', models.CharField(max_length=50, verbose_name='Andar/Pavimento')),
                ('tipo_peca', models.CharField(max_length=100, verbose_name='Peça/Componente')),
                ('data_registro', models.DateField(auto_now_add=True, verbose_name='Data de Registro')),
                ('data_previsao_troca', models.DateField(verbose_name='Previsão de Troca')),
                ('tecnico', models.CharField(blank=True, max_length=200, null=True, verbose_name='Técnico Responsável')),
                ('data_efetiva_troca', models.DateField(blank=True, null=True, verbose_name='Data Efetiva da Troca')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('SUBSTITUIDA', 'Substituída')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
