# Generated by Django 6.0 on 2026-07-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevadores', '0005_pecamanutencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevadorstatus',
            name='programacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Programação Especial'),
        ),
        migrations.AlterField(
            model_name='elevadorstatus',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'ATIVO'), ('PARADO', 'PARADO'), ('PROGRAMADO', 'PROGRAMADO')], default='ATIVO', max_length=10, verbose_name='Status Atual'),
        ),
        migrations.AlterField(
            model_name='elevorderreg',
            name='elevador_parado',
            field=models.CharField(choices=[('ATIVO', 'ATIVO'), ('PARADO', 'PARADO'), ('PROGRAMADO', 'PROGRAMADO')], max_length=10, null=True, verbose_name='Status do Elevador'),
        ),
    ]
