# Generated by Django 6.0 on 2026-07-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevadores', '0006_elevadorstatus_programacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevadorstatus',
            name='motivo_programacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo da Programação'),
        ),
    ]
