# Generated by Django 6.0 on 2026-07-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevadores', '0007_elevadorstatus_motivo_programacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecamanutencao',
            name='ordem_servico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ordem de Serviço (Origem)'),
        ),
        migrations.AddField(
            model_name='pecamanutencao',
            name='tecnico_identificador',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Técnico Identificador'),
        ),
    ]
