# Generated by Django 6.0 on 2026-07-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevadores', '0008_pecamanutencao_ordem_servico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevadorParadaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevador', models.CharField(choices=[('Social 1 - M2674', 'Social 1 - M2674'), ('Social 2 - M2675', 'Social 2 - M2675'), ('Social 3 - M2676', 'Social 3 - M2676'), ('Social 4 - M2677', 'Social 4 - M2677'), ('Social 5 - M2678', 'Social 5 - M2678'), ('Serviço 6 - M2679', 'Serviço 6 - M2679'), ('Privativo 7 - M2680', 'Privativo 7 - M2680'), ('Social 8 - M2681', 'Social 8 - M2681'), ('Social 9 - M2682', 'Social 9 - M2682'), ('Privativo 10 - M2683', 'Privativo 10 - M2683'), ('Social 11 - M2684', 'Social 11 - M2684'), ('Social 12 - M2685', 'Social 12 - M2685'), ('Social 13 - M2686', 'Social 13 - M2686'), ('Serviço 14 - M2687', 'Serviço 14 - M2687')], max_length=50, verbose_name='Elevador')),
                ('data_hora_parada', models.DateTimeField(verbose_name='Data e Hora da Parada')),
                ('data_hora_retorno', models.DateTimeField(verbose_name='Data e Hora do Retorno')),
                ('tempo_parado', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Horas Úteis Parado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
