# Generated by Django 6.0 on 2026-07-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevadores', '0009_elevadorparadahistorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevadorstatus',
            name='programacao_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim da Programação'),
        ),
        migrations.AddField(
            model_name='elevadorstatus',
            name='programacao_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início da Programação'),
        ),
    ]
