# Generated by Django 5.2.8 on 2026-07-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevadores', '0012_alter_categoria_id_alter_elevadorparadahistorico_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevorderreg',
            name='alarme_ems',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=3, null=True, verbose_name='Alarme EMS'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='elevadorparadahistorico',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='elevadorstatus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='elevorderreg',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='manutencaopreventiva',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pecamanutencao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
