# Generated by Django 5.2.8 on 2026-07-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevadores', '0013_elevorderreg_alarme_ems_alter_categoria_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevorderreg',
            name='alarme_ems',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alarme EMS'),
        ),
    ]
