# Generated by Django 5.2.8 on 2026-07-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevadores', '0014_alter_elevorderreg_alarme_ems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevorderreg',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'ABERTA'), ('CONCLUIDA', 'CONCLUIDA'), ('AGUARDANDO PEÇAS', 'AGUARDANDO PEÇAS')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pecamanutencao',
            name='andar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Andar/Pavimento'),
        ),
        migrations.AlterField(
            model_name='pecamanutencao',
            name='data_previsao_troca',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão de Troca'),
        ),
    ]
