# Generated by Django 5.2.8 on 2026-07-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevadores', '0015_alter_elevorderreg_status_alter_pecamanutencao_andar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevorderreg',
            name='acompanhante',
            field=models.CharField(blank=True, help_text='Nome do usuário que acompanhou o técnico.', max_length=200, null=True, verbose_name='Acompanhante'),
        ),
        migrations.AlterField(
            model_name='elevorderreg',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'ABERTA'), ('EM ANDAMENTO', 'EM ANDAMENTO'), ('CONCLUIDA', 'CONCLUIDA'), ('AGUARDANDO PEÇAS', 'AGUARDANDO PEÇAS')], max_length=20, verbose_name='Status'),
        ),
    ]
