# Generated by Django 5.2.8 on 2026-07-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevadores', '0016_elevorderreg_acompanhante_alter_elevorderreg_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevorderreg',
            name='registrador_chegada',
            field=models.CharField(blank=True, help_text='Usuário que registrou a chegada do técnico.', max_length=200, null=True, verbose_name='Registrado por'),
        ),
    ]
