# Generated by Django 5.2.8 on 2026-07-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevadores', '0017_elevorderreg_registrador_chegada'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmeEmsEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('EVENT', 'EVENT'), ('ALARM', 'ALARM')], max_length=10, verbose_name='Tipo de Evento')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora do Evento')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('elevador', models.CharField(choices=[('Social 1 - M2674', 'Social 1 - M2674'), ('Social 2 - M2675', 'Social 2 - M2675'), ('Social 3 - M2676', 'Social 3 - M2676'), ('Social 4 - M2677', 'Social 4 - M2677'), ('Social 5 - M2678', 'Social 5 - M2678'), ('Serviço 6 - M2679', 'Serviço 6 - M2679'), ('Privativo 7 - M2680', 'Privativo 7 - M2680'), ('Social 8 - M2681', 'Social 8 - M2681'), ('Social 9 - M2682', 'Social 9 - M2682'), ('Privativo 10 - M2683', 'Privativo 10 - M2683'), ('Social 11 - M2684', 'Social 11 - M2684'), ('Social 12 - M2685', 'Social 12 - M2685'), ('Social 13 - M2686', 'Social 13 - M2686'), ('Serviço 14 - M2687', 'Serviço 14 - M2687')], max_length=50, verbose_name='Elevador')),
                ('usuario_registrador', models.CharField(blank=True, max_length=150, null=True, verbose_name='Usuário Registrador')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
