# Generated by Django 5.2.8 on 2026-07-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevadores', '0018_alarmeemsevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevorderreg',
            name='justificativa_parada',
            field=models.TextField(blank=True, help_text='Descreva o motivo da continuidade da parada.', null=True, verbose_name='Justificativa da Parada'),
        ),
    ]
