# Generated by Django 5.2.8 on 2026-07-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevadores', '0019_elevorderreg_justificativa_parada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecamanutencao',
            name='valor_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Estimado'),
        ),
        migrations.AlterField(
            model_name='elevorderreg',
            name='atendente',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Atendente'),
        ),
        migrations.AlterField(
            model_name='elevorderreg',
            name='protocolo',
            field=models.CharField(blank=True, error_messages={'max_length': 'O protocolo excedeu o número máximo de caracteres permitidos (20).', 'unique': 'Este protocolo já existe. Por favor, verifique e tente novamente.'}, help_text='Digite o protocolo da OS, ex: 123456789...', max_length=20, null=True, unique=True, verbose_name='Protocolo'),
        ),
    ]
