# Generated by Django 5.2.8 on 2026-07-20 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_contratos_app_vinculado'),
        ('elevadores', '0020_pecamanutencao_valor_estimado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencaopreventiva',
            name='apresentacao',
            field=models.CharField(choices=[('OK', 'OK'), ('NOK', 'NOK'), ('NA', 'N/A')], default='OK', max_length=5, verbose_name='Apresentação'),
        ),
        migrations.AddField(
            model_name='manutencaopreventiva',
            name='cliente_comentarios',
            field=models.TextField(blank=True, null=True, verbose_name='Comentários do cliente'),
        ),
        migrations.AddField(
            model_name='manutencaopreventiva',
            name='cliente_data',
            field=models.DateField(blank=True, null=True, verbose_name='Data Visto'),
        ),
        migrations.AddField(
            model_name='manutencaopreventiva',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Cliente'),
        ),
        migrations.AddField(
            model_name='manutencaopreventiva',
            name='cliente_nome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Cliente (Visto)'),
        ),
        migrations.AddField(
            model_name='manutencaopreventiva',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.contratos', verbose_name='Contrato Cliente'),
        ),
        migrations.AddField(
            model_name='manutencaopreventiva',
            name='controle',
            field=models.CharField(choices=[('OK', 'OK'), ('NOK', 'NOK'), ('NA', 'N/A')], default='OK', max_length=5, verbose_name='Controle (EL)'),
        ),
        migrations.AddField(
            model_name='manutencaopreventiva',
            name='descricao_servico',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do serviço executado / a executar'),
        ),
        migrations.AddField(
            model_name='manutencaopreventiva',
            name='encerramento',
            field=models.CharField(choices=[('OK', 'OK'), ('NOK', 'NOK'), ('NA', 'N/A')], default='OK', max_length=5, verbose_name='Encerramento'),
        ),
        migrations.AddField(
            model_name='manutencaopreventiva',
            name='foto_poco',
            field=models.ImageField(blank=True, null=True, upload_to='mpm_fotos/', verbose_name='Foto Poço'),
        ),
        migrations.AddField(
            model_name='manutencaopreventiva',
            name='hora_chegada',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Chegada'),
        ),
        migrations.AddField(
            model_name='manutencaopreventiva',
            name='hora_saida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Saída'),
        ),
        migrations.AddField(
            model_name='manutencaopreventiva',
            name='limitador_velocidade',
            field=models.CharField(choices=[('OK', 'OK'), ('NOK', 'NOK'), ('NA', 'N/A')], default='OK', max_length=5, verbose_name='Limitador Velocidade (P)'),
        ),
        migrations.AddField(
            model_name='manutencaopreventiva',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='manutencaopreventiva',
            name='performance_qualidade',
            field=models.CharField(choices=[('OK', 'OK'), ('NOK', 'NOK'), ('NA', 'N/A')], default='OK', max_length=5, verbose_name='Performance de qualidade'),
        ),
        migrations.AddField(
            model_name='manutencaopreventiva',
            name='poco',
            field=models.CharField(choices=[('OK', 'OK'), ('NOK', 'NOK'), ('NA', 'N/A')], default='OK', max_length=5, verbose_name='Poço (P)'),
        ),
        migrations.AddField(
            model_name='manutencaopreventiva',
            name='situacao_equipamento',
            field=models.CharField(choices=[('Em Funcionamento', 'Em Funcionamento'), ('Parado', 'Parado')], default='Em Funcionamento', max_length=50, verbose_name='Situação do Equipamento'),
        ),
        migrations.AddField(
            model_name='manutencaopreventiva',
            name='tecnico_chapa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chapa do Técnico'),
        ),
    ]
