# Generated by Django 5.2.8 on 2026-07-20 20:19

import sesen_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevadores', '0021_manutencaopreventiva_apresentacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevorderreg',
            name='midia',
            field=models.FileField(blank=True, null=True, upload_to=sesen_app.utils.dinamic_upload_path, verbose_name='Anexo/Mídia'),
        ),
        migrations.AddField(
            model_name='manutencaopreventiva',
            name='midia',
            field=models.FileField(blank=True, null=True, upload_to=sesen_app.utils.dinamic_upload_path, verbose_name='Anexo/Mídia'),
        ),
        migrations.AddField(
            model_name='pecamanutencao',
            name='midia',
            field=models.FileField(blank=True, null=True, upload_to=sesen_app.utils.dinamic_upload_path, verbose_name='Anexo/Mídia'),
        ),
        migrations.AlterField(
            model_name='manutencaopreventiva',
            name='cliente_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
