# Generated by Django 5.2.8 on 2026-07-21 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevadores', '0022_elevorderreg_midia_manutencaopreventiva_midia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevadorparadahistorico',
            name='os_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paradas_historico', to='elevadores.elevorderreg', verbose_name='OS Relacionada'),
        ),
    ]
