# Generated by Django 5.2.8 on 2026-07-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevadores', '0023_elevadorparadahistorico_os_relacionada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevadorparadahistorico',
            name='data_hora_retorno',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora do Retorno'),
        ),
    ]
