# Generated by Django 5.2.8 on 2026-07-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevadores', '0026_alter_alarmeemsevent_elevador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevorderreg',
            name='elevadores_afetados',
            field=models.JSONField(blank=True, null=True, verbose_name='Elevadores Afetados (EMS/Geral)'),
        ),
    ]
