# Generated by Django 5.2.8 on 2026-08-04 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevadores', '0027_elevorderreg_elevadores_afetados'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencaopreventiva',
            name='supervisor_local',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Supervisor Local (Técnico Sesen)'),
        ),
        migrations.AlterField(
            model_name='manutencaopreventiva',
            name='elevador',
            field=models.CharField(blank=True, choices=[('Geral, Elevadores 1 ao 14', 'Geral, Elevadores 1 ao 14'), ('Sistema EMS', 'Sistema EMS'), ('Social 1 - M2674', 'Social 1 - M2674'), ('Social 2 - M2675', 'Social 2 - M2675'), ('Social 3 - M2676', 'Social 3 - M2676'), ('Social 4 - M2677', 'Social 4 - M2677'), ('Social 5 - M2678', 'Social 5 - M2678'), ('Serviço 6 - M2679', 'Serviço 6 - M2679'), ('Privativo 7 - M2680', 'Privativo 7 - M2680'), ('Social 8 - M2681', 'Social 8 - M2681'), ('Social 9 - M2682', 'Social 9 - M2682'), ('Privativo 10 - M2683', 'Privativo 10 - M2683'), ('Social 11 - M2684', 'Social 11 - M2684'), ('Social 12 - M2685', 'Social 12 - M2685'), ('Social 13 - M2686', 'Social 13 - M2686'), ('Serviço 14 - M2687', 'Serviço 14 - M2687')], help_text='[LEGADO] Mantido para compatibilidade.', max_length=50, null=True, verbose_name='Elevador'),
        ),
        migrations.AlterField(
            model_name='manutencaopreventiva',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='RegistroElevadorPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevador', models.CharField(choices=[('Geral, Elevadores 1 ao 14', 'Geral, Elevadores 1 ao 14'), ('Sistema EMS', 'Sistema EMS'), ('Social 1 - M2674', 'Social 1 - M2674'), ('Social 2 - M2675', 'Social 2 - M2675'), ('Social 3 - M2676', 'Social 3 - M2676'), ('Social 4 - M2677', 'Social 4 - M2677'), ('Social 5 - M2678', 'Social 5 - M2678'), ('Serviço 6 - M2679', 'Serviço 6 - M2679'), ('Privativo 7 - M2680', 'Privativo 7 - M2680'), ('Social 8 - M2681', 'Social 8 - M2681'), ('Social 9 - M2682', 'Social 9 - M2682'), ('Privativo 10 - M2683', 'Privativo 10 - M2683'), ('Social 11 - M2684', 'Social 11 - M2684'), ('Social 12 - M2685', 'Social 12 - M2685'), ('Social 13 - M2686', 'Social 13 - M2686'), ('Serviço 14 - M2687', 'Serviço 14 - M2687')], max_length=50, verbose_name='Elevador')),
                ('situacao', models.CharField(choices=[('Em Funcionamento', 'Em Funcionamento'), ('Parado', 'Parado')], default='Em Funcionamento', max_length=50, verbose_name='Situação do Equipamento')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora Início')),
                ('hora_fim', models.TimeField(blank=True, null=True, verbose_name='Hora Fim')),
                ('manutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elevadores_registrados', to='elevadores.manutencaopreventiva', verbose_name='Manutenção Preventiva Mestre')),
            ],
        ),
    ]
