# Generated by Django 6.0 on 2026-06-01 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AparelhoVoip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.CharField(max_length=10, null=True)),
                ('modelo', models.CharField(max_length=30, null=True)),
                ('mac_address', models.CharField(max_length=20, null=True)),
                ('ramal', models.CharField(max_length=10, null=True)),
                ('integridade', models.CharField(choices=[('perfeito', 'Perfeito'), ('bom_estado', 'Bom Estado'), ('regular', 'Regular'), ('ruim', 'Ruim'), ('critico', 'Crítico')], default='perfeito', max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelefoneSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(help_text='Data e Hora que a solicitação chegou na seção')),
                ('protocolo', models.CharField(help_text='Protocolo SEI do Documento', max_length=20, null=True, unique=True)),
                ('unidade', models.CharField(max_length=200, null=True)),
                ('sigla_unidade', models.CharField(max_length=20, null=True)),
                ('local', models.CharField(max_length=20, null=True)),
                ('qnt_solicitada', models.IntegerField()),
                ('solicitante', models.CharField(help_text='Nome de quem assinou o pedido', max_length=100)),
                ('tecnico_avaliou', models.CharField(max_length=200, null=True)),
                ('avaliacao', models.CharField(max_length=500, null=True)),
                ('autorizacao_sad', models.CharField(help_text='Protocolo SEI do Documento que autoriza a instalação', max_length=20, null=True, unique=True)),
                ('tecnico_instalou', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('recebida', 'Recebida'), ('em_analise', 'Em Análise'), ('pendente', 'Pendente'), ('concluida', 'Concluída')], default='recebida', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AparelhoDefeito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_defeito', models.DateTimeField()),
                ('defeito', models.CharField(max_length=500, null=True)),
                ('data_retirada_plaqueta', models.DateTimeField()),
                ('memo_solicitacao_baixa', models.DateTimeField()),
                ('data_baixa_patrimonio', models.DateTimeField()),
                ('data_saida_manutencao', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aparelho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_defeitos', to='telefonia.aparelhovoip')),
            ],
        ),
    ]
