# Generated by Django 6.0 on 2026-06-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriarSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(help_text='Protocolo SEI do Documento', max_length=20, null=True, unique=True)),
                ('unidade', models.CharField(max_length=200, null=True)),
                ('sigla_unidade', models.CharField(max_length=20, null=True)),
                ('ramal', models.CharField(max_length=10, null=True)),
                ('usuario', models.CharField(max_length=30, null=True)),
                ('solicitante', models.CharField(help_text='Nome de quem assinou o pedido', max_length=100, null=True)),
                ('categoria', models.CharField(max_length=10, null=True)),
                ('desvio', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False)),
                ('tel_desvio_externo', models.CharField(max_length=30, null=True)),
                ('nome_tecnico', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
