# Generated by Django 6.0 on 2026-07-01 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0002_criarsenha'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparelhovoip',
            name='fcn',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='aparelhovoip',
            name='status',
            field=models.CharField(choices=[('estoque', 'Em Estoque'), ('instalado', 'Instalado'), ('defeituoso', 'Defeituoso')], default='estoque', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='telefonesolicitacao',
            name='patrimonio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacao_vinculada', to='telefonia.aparelhovoip'),
        ),
        migrations.AddField(
            model_name='telefonesolicitacao',
            name='ramal',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aparelhovoip',
            name='ramal',
            field=models.CharField(blank=True, help_text='Preenchido automaticamente via Solicitação de Aparelho', max_length=10, null=True),
        ),
    ]
