# Generated by Django 6.0 on 2026-07-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0003_aparelhovoip_fcn_aparelhovoip_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefonesolicitacao',
            name='patrimonio',
        ),
        migrations.AddField(
            model_name='telefonesolicitacao',
            name='aparelhos',
            field=models.ManyToManyField(blank=True, related_name='solicitacoes_vinculadas', to='telefonia.aparelhovoip'),
        ),
    ]
