# Generated by Django 6.0 on 2026-07-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0004_remove_telefonesolicitacao_patrimonio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparelhovoip',
            name='ramal',
            field=models.CharField(blank=True, help_text='Preenchido automaticamente via Solicitação de Aparelho', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telefonesolicitacao',
            name='local',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='telefonesolicitacao',
            name='ramal',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
