# Generated by Django 6.0 on 2026-07-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0005_alter_aparelhovoip_ramal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparelhovoip',
            name='integridade',
            field=models.CharField(choices=[('funciona', 'Funciona'), ('defeito', 'Defeito')], default='funciona', max_length=30, null=True),
        ),
    ]
