# Generated by Django 6.0 on 2026-07-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0006_alter_aparelhovoip_integridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefonesolicitacao',
            name='avaliacao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='telefonesolicitacao',
            name='ramal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='telefonesolicitacao',
            name='tecnico_avaliou',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='telefonesolicitacao',
            name='tecnico_instalou',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
