# Generated by Django 6.0 on 2026-07-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0007_alter_telefonesolicitacao_avaliacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparelhovoip',
            name='sala',
            field=models.CharField(blank=True, help_text='Preenchido automaticamente via Solicitação de Aparelho', max_length=200, null=True),
        ),
    ]
