# Generated by Django 6.0 on 2026-07-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0008_aparelhovoip_sala'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemessaManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memorando', models.CharField(help_text='Nº do Memorando (ex: Memorando SESEN/COSEN/SAD nº 142/2026)', max_length=100)),
                ('data_remessa', models.DateTimeField(auto_now_add=True)),
                ('empresa_contratada', models.CharField(default='3CORP TECHNOLOGY LTDA.', max_length=200)),
                ('contrato_tse', models.CharField(default='Contrato TSE nº 40/2021', max_length=100)),
                ('aparelhos', models.ManyToManyField(related_name='remessas_manutencao', to='telefonia.aparelhovoip')),
            ],
        ),
        migrations.DeleteModel(
            name='AparelhoDefeito',
        ),
    ]
