# Generated by Django 6.0 on 2026-07-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0009_remessamanutencao_delete_aparelhodefeito'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefonesolicitacao',
            name='data_instalacao',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que a instalação foi concluída', null=True),
        ),
    ]
