# Generated by Django 6.0 on 2026-07-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0010_telefonesolicitacao_data_instalacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telefonesolicitacao',
            old_name='tecnico_instalou',
            new_name='tecnico_responsavel',
        ),
        migrations.RemoveField(
            model_name='telefonesolicitacao',
            name='tecnico_avaliou',
        ),
    ]
