# Generated by Django 6.0 on 2026-07-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0011_rename_tecnico_instalou_telefonesolicitacao_tecnico_responsavel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telefonesolicitacao',
            old_name='avaliacao',
            new_name='relatorio',
        ),
    ]
