# Generated by Django 6.0 on 2026-07-06 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0013_remove_unique_constraints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remessamanutencao',
            name='aparelhos',
        ),
        migrations.CreateModel(
            name='AparelhoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.CharField(max_length=10, null=True)),
                ('modelo', models.CharField(max_length=30, null=True)),
                ('fcn', models.CharField(max_length=15, null=True)),
                ('mac_address', models.CharField(max_length=20, null=True)),
                ('ramal', models.CharField(blank=True, max_length=100, null=True)),
                ('sala', models.CharField(blank=True, max_length=200, null=True)),
                ('integridade', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remessa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aparelhos_manutencao', to='telefonia.remessamanutencao')),
            ],
        ),
    ]
