# Generated by Django 6.0 on 2026-07-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0014_remove_remessamanutencao_aparelhos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criarsenha',
            name='edificios',
            field=models.CharField(blank=True, default='Ed. Sede/Anexo', help_text='Edifícios onde pode ser utilizada', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='criarsenha',
            name='senha',
            field=models.CharField(blank=True, help_text='Senha registrada', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='criarsenha',
            name='usuario',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
