# Generated by Django 6.0 on 2026-07-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0015_criarsenha_edificios_criarsenha_senha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefonesolicitacao',
            name='termo_transferencia_interna',
            field=models.CharField(blank=True, help_text='Ex: 2026/002199', max_length=50, null=True),
        ),
    ]
