# Generated by Django 6.0 on 2026-07-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0017_padraosenhatelefonia'),
    ]

    operations = [
        migrations.AddField(
            model_name='padraosenhatelefonia',
            name='nome',
            field=models.CharField(default='Template Padrão', max_length=100, verbose_name='Nome do Template'),
        ),
    ]
