# Generated by Django 6.0 on 2026-07-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0018_padraosenhatelefonia_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='padraosenhatelefonia',
            name='cabecalho_logo',
            field=models.CharField(default='TSE', max_length=50, verbose_name='Logo (Texto grande)'),
        ),
        migrations.AddField(
            model_name='padraosenhatelefonia',
            name='cabecalho_sublogo',
            field=models.CharField(default='Tribunal Superior Eleitoral', max_length=150, verbose_name='Sub-logo (Texto menor abaixo da logo)'),
        ),
        migrations.AddField(
            model_name='padraosenhatelefonia',
            name='cabecalho_subtitulo',
            field=models.CharField(default='Secretaria de Administração | COSEN - SESEN', max_length=200, verbose_name='Subtítulo do Cabeçalho (Lado Direito)'),
        ),
    ]
