# Generated by Django 6.0 on 2026-07-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0019_padraosenhatelefonia_cabecalho_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criarsenha',
            name='email',
            field=models.EmailField(blank=True, help_text='E-mail Institucional', max_length=255, null=True),
        ),
    ]
