# Generated by Django 6.0 on 2026-07-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0021_padraotutorialtelefonia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PadraoEmailTelefonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Template Padrão', max_length=100, verbose_name='Nome do Template')),
                ('assunto', models.CharField(default='Senha Telefônica', max_length=200, verbose_name='Assunto do E-mail')),
                ('corpo', models.TextField(help_text='Variáveis permitidas: {primeiro_nome}, {senha}, {assinatura}', verbose_name='Corpo da Mensagem')),
                ('assinatura', models.TextField(default='Seção de Equipamentos e Sistemas de Engenharia\nTelefone/Ramal: 61 3030-8224', verbose_name='Assinatura da Seção')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Padrão de E-mail de Telefonia',
                'verbose_name_plural': 'Padrões de E-mail de Telefonia',
            },
        ),
    ]
