# Generated by Django 6.0 on 2026-07-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0022_padraoemailtelefonia'),
    ]

    operations = [
        migrations.AddField(
            model_name='padraoemailtelefonia',
            name='email_copia',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail em Cópia Oculta (BCC)'),
        ),
    ]
