# Generated by Django 6.0 on 2026-07-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0023_padraoemailtelefonia_email_copia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criarsenha',
            name='usuario',
        ),
        migrations.AddField(
            model_name='criarsenha',
            name='cargo',
            field=models.CharField(choices=[('servidor', 'Servidor'), ('colaborador', 'Colaborador')], default='servidor', max_length=20),
        ),
        migrations.AddField(
            model_name='criarsenha',
            name='empresa_vinculada',
            field=models.CharField(blank=True, help_text='Apenas para Colaboradores', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='criarsenha',
            name='fiscal_contrato',
            field=models.CharField(blank=True, help_text='Apenas para Colaboradores', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='criarsenha',
            name='numero_contrato',
            field=models.CharField(blank=True, help_text='Apenas para Colaboradores', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='criarsenha',
            name='primeiro_nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='criarsenha',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
