# Generated by Django 6.0 on 2026-07-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0024_remove_criarsenha_usuario_criarsenha_cargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, unique=True, verbose_name='Número do Contrato')),
                ('empresa_vinculada', models.CharField(max_length=100, verbose_name='Empresa Vinculada')),
                ('fiscal_contrato', models.CharField(max_length=100, verbose_name='Fiscal do Contrato')),
                ('unidade_fiscal', models.CharField(blank=True, max_length=200, null=True, verbose_name='Unidade de Lotação do Fiscal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='criarsenha',
            name='unidade_fiscal',
            field=models.CharField(blank=True, help_text='Unidade de Lotação do Fiscal (Apenas Colaboradores)', max_length=200, null=True),
        ),
    ]
