# Generated by Django 6.0 on 2026-07-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0025_contratocolaborador_criarsenha_unidade_fiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparelhovoip',
            name='fcn',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='aparelhovoip',
            name='integridade',
            field=models.CharField(choices=[('perfeito', 'Perfeito'), ('bom_estado', 'Bom Estado'), ('regular', 'Regular'), ('ruim', 'Ruim'), ('critico', 'Crítico')], default='perfeito', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='aparelhovoip',
            name='ramal',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aparelhovoip',
            name='sala',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aparelhovoip',
            name='status',
            field=models.CharField(choices=[('estoque', 'Em Estoque'), ('instalado', 'Instalado'), ('manutencao', 'Em Manutenção'), ('defeituoso', 'Defeituoso')], default='estoque', max_length=20),
        ),
        migrations.AlterField(
            model_name='telefonesolicitacao',
            name='aparelhos',
            field=models.ManyToManyField(blank=True, related_name='solicitacoes', to='telefonia.aparelhovoip'),
        ),
        migrations.AlterField(
            model_name='telefonesolicitacao',
            name='data_instalacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telefonesolicitacao',
            name='local',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='telefonesolicitacao',
            name='ramal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='telefonesolicitacao',
            name='relatorio',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='telefonesolicitacao',
            name='tecnico_responsavel',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='telefonesolicitacao',
            name='termo_transferencia_interna',
            field=models.FileField(blank=True, null=True, upload_to='termos/'),
        ),
    ]
