# Generated by Django 6.0 on 2026-07-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0026_alter_aparelhovoip_fcn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefonesolicitacao',
            name='termo_transferencia_interna',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
