# Generated by Django 6.0 on 2026-07-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0027_alter_telefonesolicitacao_termo_transferencia_interna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefonesolicitacao',
            name='local',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
