# Generated by Django 6.0 on 2026-07-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0030_alter_aparelhomanutencao_id_alter_aparelhovoip_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criarsenha',
            name='protocolo',
            field=models.CharField(help_text='Protocolo SEI do Documento', max_length=20, null=True),
        ),
    ]
