# Generated by Django 6.0 on 2026-07-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0031_alter_criarsenha_protocolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='criarsenha',
            name='status',
            field=models.CharField(choices=[('recebida', 'Recebida'), ('aguardando_supervisor', 'Aguardando Supervisor'), ('finalizada', 'Finalizada')], default='recebida', max_length=50, null=True),
        ),
    ]
