# Generated by Django 6.0 on 2026-07-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0032_criarsenha_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criarsenha',
            name='nome_tecnico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='criarsenha',
            name='tel_desvio_externo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
