# Generated by Django 6.0 on 2026-07-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0035_alter_aparelhomanutencao_id_alter_aparelhovoip_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefonesolicitacao',
            name='midia',
            field=models.FileField(blank=True, help_text='Anexo ou mídia para a solicitação', null=True, upload_to='telefonia/midia/solicitacoes/'),
        ),
    ]
