# Generated by Django 5.2.8 on 2026-07-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0036_telefonesolicitacao_midia'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparelhovoip',
            name='funcao_aparelho',
            field=models.CharField(choices=[('fixo', 'Fixo'), ('eventos', 'Eventos')], default='fixo', max_length=20),
        ),
        migrations.CreateModel(
            name='EmprestimoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_nome', models.CharField(help_text='Nome ou descrição do evento', max_length=255)),
                ('data_inicio', models.DateTimeField(help_text='Data e hora de início do empréstimo')),
                ('data_fim', models.DateTimeField(help_text='Data e hora prevista para encerramento e recolhimento')),
                ('solicitante', models.CharField(help_text='Nome do solicitante', max_length=255)),
                ('tecnico_responsavel', models.CharField(blank=True, help_text='Técnico responsável pela instalação', max_length=255, null=True)),
                ('local', models.CharField(help_text='Local de instalação no evento', max_length=255)),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('concluido', 'Concluído/Recolhido')], default='em_andamento', max_length=20)),
                ('observacoes', models.TextField(blank=True, help_text='Observações gerais ou motivos de problemas no recolhimento', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aparelhos', models.ManyToManyField(blank=True, related_name='emprestimos_evento', to='telefonia.aparelhovoip')),
            ],
        ),
    ]
