# Generated by Django 5.2.8 on 2026-07-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0037_aparelhovoip_funcao_aparelho_emprestimoevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimoevento',
            name='notificacao_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
