# Generated by Django 6.0 on 2026-08-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0038_emprestimoevento_notificacao_enviada'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefonesolicitacao',
            name='pdf_termo',
            field=models.FileField(blank=True, help_text='PDF do Relatório de Transferência', null=True, upload_to='telefonia/midia/termos/'),
        ),
        migrations.AlterField(
            model_name='telefonesolicitacao',
            name='status',
            field=models.CharField(choices=[('recebida', 'Recebida'), ('em_analise', 'Em Análise'), ('pendente', 'Pendente'), ('aguardando_supervisor_aparelho', 'Aguardando Supervisor'), ('concluida', 'Concluída')], default='recebida', max_length=50, null=True),
        ),
    ]
