# Generated by Django 5.2.8 on 2026-08-05 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0039_telefonesolicitacao_pdf_termo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelefoneSolicitacaoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(help_text='Arquivo anexo', upload_to='telefonia/midia/anexos_solicitacoes/')),
                ('ordem', models.IntegerField(default=0, help_text='Ordem do anexo para relacionamento com aparelhos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('solicitacao', models.ForeignKey(help_text='Solicitação vinculada', on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='telefonia.telefonesolicitacao')),
            ],
        ),
    ]
