# Generated by Django 5.2.8 on 2026-08-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0040_telefonesolicitacaoanexo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telefonesolicitacaoanexo',
            options={'ordering': ['ordem']},
        ),
    ]
