# Generated by Django 5.2.8 on 2026-08-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0041_alter_telefonesolicitacaoanexo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NadaConsta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(help_text='Protocolo SEI do documento solicitante', max_length=50)),
                ('unidade', models.CharField(help_text='Nome completo da unidade solicitante', max_length=200)),
                ('sigla_unidade', models.CharField(help_text='Sigla da unidade', max_length=20)),
                ('servidor', models.CharField(help_text='Nome completo do servidor', max_length=200)),
                ('data', models.DateTimeField(help_text='Data e hora da solicitação')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída')], default='pendente', max_length=20)),
                ('ramal', models.CharField(blank=True, help_text='Ramal utilizado pelo servidor', max_length=50, null=True)),
                ('email_cadastrado', models.CharField(blank=True, help_text='E-mail cadastrado no sistema de tarifação', max_length=200, null=True)),
                ('valor_devido', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor devido em R$', max_digits=10)),
                ('pdf_fatura', models.FileField(blank=True, help_text='Fatura em PDF se houver valor devido', null=True, upload_to='telefonia/midia/nada_consta/')),
                ('tecnico_responsavel', models.CharField(blank=True, help_text='Técnico que concluiu a solicitação', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nada Consta',
                'verbose_name_plural': 'Nada Constas',
                'ordering': ['-data'],
            },
        ),
    ]
