# Generated by Django 5.2.8 on 2026-08-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0042_nadaconsta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PadraoNadaConstaTelefonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Template Padrão', max_length=100, verbose_name='Nome do Template')),
                ('cabecalho_logo', models.CharField(default='TRIBUNAL SUPERIOR ELEITORAL', max_length=150, verbose_name='Cabeçalho: Órgão Principal')),
                ('cabecalho_sublogo1', models.CharField(default='SECRETARIA DE TECNOLOGIA DA INFORMAÇÃO', max_length=150, verbose_name='Cabeçalho: Secretaria')),
                ('cabecalho_sublogo2', models.CharField(default='SEÇÃO DE TELEFONIA', max_length=150, verbose_name='Cabeçalho: Seção')),
                ('titulo_documento', models.CharField(default='INFORMATIVO DE DÉBITO - TELEFONIA', max_length=150, verbose_name='Título do Documento')),
                ('paragrafo_introdutorio', models.TextField(default='Em resposta à solicitação de Nada Consta (Protocolo SEI nº {protocolo}), informamos que após verificação no sistema de tarifação desta Seção de Telefonia, foi constatado débito pendente em nome do(a) servidor(a) {servidor}, da unidade {unidade} ({sigla_unidade}).', help_text='Use as tags {protocolo}, {servidor}, {unidade}, {sigla_unidade} para substituir dinamicamente.', verbose_name='Parágrafo Introdutório')),
                ('paragrafo_dados_vinculados', models.TextField(default='Os dados vinculados ao servidor no sistema são:\nRamal: {ramal}\nE-mail Cadastrado: {email}', help_text='Use as tags {ramal}, {email}.', verbose_name='Dados Vinculados')),
                ('descricao_debito', models.CharField(default='Débito referente à utilização do sistema de telefonia (faturas pendentes)', max_length=255, verbose_name='Descrição do Débito (Tabela)')),
                ('paragrafo_conclusao', models.TextField(default='Solicita-se que o referido valor seja recolhido via Guia de Recolhimento da União (GRU) e o comprovante anexado ao processo SEI para a devida quitação e emissão do Nada Consta definitivo.', verbose_name='Parágrafo Conclusivo')),
                ('assinatura_secao', models.CharField(default='Seção de Telefonia - TSE', max_length=150, verbose_name='Assinatura: Seção')),
                ('assinatura_local', models.CharField(default='Brasília, {data}', help_text='Use {data} para a data atual formatada.', max_length=150, verbose_name='Assinatura: Local e Data')),
                ('ativo', models.BooleanField(default=True, help_text='Apenas o padrão marcado como ATIVO será exibido na geração dos PDFs de fatura de Nada Consta.')),
            ],
            options={
                'verbose_name': 'Padrão de Documento (Nada Consta)',
                'verbose_name_plural': 'Padrões de Documento (Nada Constas)',
            },
        ),
    ]
