# Generated by Django 5.2.8 on 2026-08-18 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0043_padraonadaconstatelefonia'),
    ]

    operations = [
        migrations.AddField(
            model_name='criarsenha',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Senha Ativa'),
        ),
        migrations.AddField(
            model_name='nadaconsta',
            name='aparelho_vinculado',
            field=models.ForeignKey(blank=True, help_text='Aparelho vinculado ao ramal da senha', null=True, on_delete=django.db.models.deletion.SET_NULL, to='telefonia.aparelhovoip'),
        ),
        migrations.AddField(
            model_name='nadaconsta',
            name='senha_vinculada',
            field=models.ForeignKey(blank=True, help_text='Senha vinculada encontrada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='telefonia.criarsenha'),
        ),
        migrations.AddField(
            model_name='nadaconsta',
            name='solicitar_desvinculacao',
            field=models.BooleanField(default=False, help_text='Inativar senha e solicitar retirada do nome do ramal'),
        ),
    ]
