# Generated by Django 5.2.8 on 2026-10-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0044_criarsenha_ativo_nadaconsta_aparelho_vinculado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criarsenha',
            name='cancelado_por',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='criarsenha',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criarsenha',
            name='justificativa_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nadaconsta',
            name='cancelado_por',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='nadaconsta',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nadaconsta',
            name='justificativa_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
