# Generated by Django 6.0 on 2026-10-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0045_criarsenha_cancelado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nadaconsta',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20),
        ),
    ]
