# Generated by Django 6.0 on 2026-10-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0046_alter_nadaconsta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criarsenha',
            name='status',
            field=models.CharField(choices=[('recebida', 'Recebida'), ('aguardando_supervisor', 'Aguardando Supervisor'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='recebida', max_length=50, null=True),
        ),
    ]
