# Generated by Django 6.0 on 2026-10-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0047_alter_criarsenha_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefonesolicitacao',
            name='cancelado_por',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='telefonesolicitacao',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telefonesolicitacao',
            name='justificativa_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telefonesolicitacao',
            name='status',
            field=models.CharField(choices=[('recebida', 'Recebida'), ('em_analise', 'Em Análise'), ('pendente', 'Pendente'), ('aguardando_supervisor_aparelho', 'Aguardando Supervisor'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='recebida', max_length=50, null=True),
        ),
    ]
