# Generated by Django 6.0 on 2026-07-29 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0021_remove_profissional_cpf_remove_profissional_email_and_more'),
        ('empresas', '0008_remove_contatoempresa_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoSEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=50, unique=True, verbose_name='Número do Processo (SEI)')),
                ('tipo', models.CharField(choices=[('PRIORITARIO', 'Prioritário'), ('TRAMITE', 'Em Trâmite'), ('CONCLUIDO', 'Concluído')], default='TRAMITE', max_length=20, verbose_name='Tipo de Monitoramento')),
                ('data_autuacao', models.DateField(blank=True, null=True, verbose_name='Data de Recebimento / Autuação')),
                ('objeto', models.TextField(blank=True, null=True, verbose_name='Objeto (Especificação)')),
                ('situacao_atual', models.TextField(blank=True, null=True, verbose_name='Situação / Tratativa Atual')),
                ('tempo_tramitacao', models.IntegerField(default=0, verbose_name='Tempo de Tramitação (dias)')),
                ('ultimo_andamento_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID do Último Andamento')),
                ('ultima_sincronizacao', models.DateTimeField(auto_now=True, verbose_name='Última Sincronização')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_sei', to='contratos.contratos')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_sei', to='empresas.empresa')),
                ('processo_licitatorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_sei', to='contratos.processolicitatorio')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoAndamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_andamento_sei', models.CharField(max_length=50)),
                ('data_hora', models.DateTimeField()),
                ('descricao', models.TextField()),
                ('unidade', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_andamentos', to='monitoramento_sei.processosei')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
