# Generated by Django 6.0 on 2026-07-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='precisa_trocar_senha',
            field=models.BooleanField(default=True, verbose_name='Precisa trocar senha no próximo login'),
        ),
    ]
