# Generated by Django 6.0 on 2026-07-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_precisa_trocar_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone (WhatsApp)'),
        ),
    ]
