# Generated by Django 6.0 on 2026-07-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfil_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='is_tecnico_telefonia',
            field=models.BooleanField(default=False, verbose_name='Técnico de Telefonia'),
        ),
    ]
