# Generated by Django 6.0 on 2026-07-10 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfil_is_tecnico_telefonia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='is_tecnico_telefonia',
        ),
    ]
