# Generated by Django 5.2.8 on 2026-07-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_perfil_email_boas_vindas_enviado_alter_perfil_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='email_boas_vindas_erro',
            field=models.TextField(blank=True, null=True, verbose_name='Erro de envio do e-mail'),
        ),
    ]
