# Generated by Django 6.0 on 2026-07-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificar_novos_usuarios', models.BooleanField(default=False, verbose_name='Notificar novos usuários via WhatsApp')),
                ('mensagem_boas_vindas', models.TextField(default='Olá, seja bem-vindo ao SesenApp!\nSeu usuário é: {usuario}\nSua senha padrão é: {senha}\n\nVocê deverá trocar sua senha no primeiro login.', help_text='Utilize {usuario} e {senha} para injetar os dados dinamicamente.', verbose_name='Mensagem de Boas-Vindas')),
            ],
            options={
                'verbose_name': 'Configuração Geral',
                'verbose_name_plural': 'Configurações Gerais',
            },
        ),
    ]
