# Generated by Django 6.0 on 2026-07-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaogeral',
            name='notificar_novos_usuarios',
            field=models.BooleanField(default=False, verbose_name='Notificar novos usuários via E-mail'),
        ),
    ]
