# Generated by Django 5.2.8 on 2026-07-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_setup', '0002_alter_configuracaogeral_notificar_novos_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaogeral',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
