# Generated by Django 6.0 on 2026-07-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_setup', '0005_alter_configuracaogeral_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaogeral',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
