# Generated by Django 5.2.8 on 2026-07-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_setup', '0006_alter_configuracaogeral_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True, verbose_name='ID da Tarefa')),
                ('nome_amigavel', models.CharField(max_length=150, verbose_name='Nome da Rotina')),
                ('intervalo_minutos', models.IntegerField(default=60, verbose_name='Intervalo em Minutos')),
                ('ativo', models.BooleanField(default=True, verbose_name='Status (Ativo/Inativo)')),
            ],
        ),
    ]
