# Generated by Django 6.0 on 2026-07-13 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Técnico')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicos', to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_solicitante', models.CharField(max_length=255, verbose_name='Nome do Solicitante')),
                ('data_solicitacao', models.DateField(verbose_name='Data da Solicitação')),
                ('validade_inicio', models.DateField(verbose_name='Validade (Início)')),
                ('validade_fim', models.DateField(verbose_name='Validade (Fim)')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('expirada', 'Expirada'), ('revogada', 'Revogada')], default='ativa', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_acesso', to='empresas.empresa')),
                ('tecnicos', models.ManyToManyField(related_name='solicitacoes_vinculadas', to='equipe_tecnica.tecnico', verbose_name='Técnicos Autorizados')),
            ],
        ),
    ]
