# Generated by Django 6.0 on 2026-07-13 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe_tecnica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PadraoEmailLiberacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Template Padrão', max_length=100, verbose_name='Nome do Template')),
                ('assunto', models.CharField(default='Liberação de Acesso', max_length=200, verbose_name='Assunto do E-mail')),
                ('email_copia', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail em Cópia Oculta (BCC)')),
                ('corpo', models.TextField(help_text='Variáveis permitidas: {empresa}, {solicitante}, {periodo}, {datas}, {tecnicos}', verbose_name='Corpo da Mensagem')),
                ('assinatura', models.TextField(default='Equipe Técnica', verbose_name='Assinatura da Seção')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Padrão de E-mail de Liberação',
                'verbose_name_plural': 'Padrões de E-mail de Liberação',
            },
        ),
        migrations.CreateModel(
            name='LiberacaoAcessoDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data Início')),
                ('data_fim', models.DateField(verbose_name='Data Fim')),
                ('periodo', models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Integral', 'Integral'), ('Noturno', 'Noturno')], default='Integral', max_length=20)),
                ('email_enviado', models.BooleanField(default=False)),
                ('data_agendamento_email', models.DateTimeField(blank=True, null=True, verbose_name='Envio Programado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liberacoes_diarias', to='equipe_tecnica.solicitacaoacesso')),
                ('tecnicos', models.ManyToManyField(related_name='liberacoes_presentes', to='equipe_tecnica.tecnico')),
            ],
        ),
    ]
