# Generated by Django 5.2.8 on 2026-07-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe_tecnica', '0002_padraoemailliberacao_liberacaoacessodiaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='padraoemailliberacao',
            name='email_destinatario',
            field=models.EmailField(blank=True, help_text='E-mail principal que receberá as comunicações de liberação de acesso', max_length=255, null=True, verbose_name='E-mail Destinatário (Segurança/Portaria)'),
        ),
        migrations.AlterField(
            model_name='liberacaoacessodiaria',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='padraoemailliberacao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='solicitacaoacesso',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
