# Generated by Django 6.0 on 2026-07-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe_tecnica', '0004_alter_liberacaoacessodiaria_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liberacaoacessodiaria',
            name='periodo',
            field=models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Integral', 'Integral'), ('Noturno', 'Noturno')], default='Integral', max_length=20),
        ),
    ]
