# Generated by Django 5.2.8 on 2026-07-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe_tecnica', '0005_alter_liberacaoacessodiaria_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liberacaoacessodiaria',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liberacaoacessodiaria',
            name='periodo',
            field=models.CharField(choices=[('Manhã', 'Matutino'), ('Tarde', 'Vespertino'), ('Integral', 'Integral'), ('Noturno', 'Noturno')], default='Integral', max_length=20),
        ),
        migrations.AlterField(
            model_name='padraoemailliberacao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='solicitacaoacesso',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
