# Generated by Django 5.2.8 on 2026-07-28 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe_tecnica', '0007_alter_liberacaoacessodiaria_id_and_more'),
        ('usuarios', '0011_pessoa_formacaoprofissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tecnicos', to='usuarios.pessoa'),
        ),
    ]
