# Generated by Django 5.2.8 on 2026-07-28 18:11

from django.db import migrations

def migrar_dados_pessoas(apps, schema_editor):
    Pessoa = apps.get_model('usuarios', 'Pessoa')
    Tecnico = apps.get_model('equipe_tecnica', 'Tecnico')
    Contato = apps.get_model('notificacoes', 'Contato')
    ServidorReembolso = apps.get_model('reembolsos', 'ServidorReembolso')

    # Migrar Tecnicos
    for tecnico in Tecnico.objects.all():
        if not tecnico.pessoa:
            if tecnico.cpf:
                pessoa, _ = Pessoa.objects.get_or_create(
                    cpf=tecnico.cpf,
                    defaults={
                        'nome': tecnico.nome,
                        'telefone': tecnico.telefone
                    }
                )
            else:
                pessoa, _ = Pessoa.objects.get_or_create(
                    nome=tecnico.nome,
                    defaults={
                        'telefone': tecnico.telefone
                    }
                )
            tecnico.pessoa = pessoa
            tecnico.save(update_fields=['pessoa'])

    # Migrar Contatos
    for contato in Contato.objects.all():
        if not contato.pessoa:
            pessoa, _ = Pessoa.objects.get_or_create(
                nome=contato.nome,
                defaults={
                    'telefone': contato.telefone
                }
            )
            contato.pessoa = pessoa
            contato.save(update_fields=['pessoa'])

    # Migrar Servidores de Reembolso
    for servidor in ServidorReembolso.objects.all():
        if not servidor.pessoa:
            if servidor.cpf:
                pessoa, _ = Pessoa.objects.get_or_create(
                    cpf=servidor.cpf,
                    defaults={
                        'nome': servidor.nome,
                    }
                )
            else:
                pessoa, _ = Pessoa.objects.get_or_create(
                    nome=servidor.nome,
                )
            servidor.pessoa = pessoa
            servidor.save(update_fields=['pessoa'])


class Migration(migrations.Migration):

    dependencies = [
        ('equipe_tecnica', '0008_tecnico_pessoa'),
        ('notificacoes', '0012_contato_pessoa'),
        ('reembolsos', '0017_servidorreembolso_pessoa'),
        ('usuarios', '0011_pessoa_formacaoprofissional'),
    ]

    operations = [
        migrations.RunPython(migrar_dados_pessoas, reverse_code=migrations.RunPython.noop),
    ]
