# Generated by Django 5.2.8 on 2026-07-28 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipe_tecnica', '0009_data_migracao_pessoas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnico',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='telefone',
        ),
    ]
