# Generated by Django 5.2.8 on 2026-08-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe_tecnica', '0010_remove_tecnico_cpf_remove_tecnico_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padraoemailliberacao',
            name='email_copia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='E-mails em Cópia Oculta (BCC)'),
        ),
        migrations.AlterField(
            model_name='padraoemailliberacao',
            name='email_destinatario',
            field=models.CharField(blank=True, help_text='E-mails principais que receberão as comunicações de liberação de acesso (separados por vírgula)', max_length=255, null=True, verbose_name='E-mails Destinatários (Segurança/Portaria)'),
        ),
    ]
