# Generated by Django 5.2.8 on 2026-08-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe_tecnica', '0011_alter_padraoemailliberacao_email_copia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liberacaoacessodiaria',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Fim'),
        ),
        migrations.AddField(
            model_name='liberacaoacessodiaria',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Início'),
        ),
    ]
