# Generated by Django 5.2.8 on 2026-08-06 16:58

from django.db import migrations


import datetime

def forwards_func(apps, schema_editor):
    LiberacaoAcessoDiaria = apps.get_model('equipe_tecnica', 'LiberacaoAcessoDiaria')
    for lib in LiberacaoAcessoDiaria.objects.all():
        if lib.periodo == 'Integral':
            lib.hora_inicio = datetime.time(8, 0)
            lib.hora_fim = datetime.time(18, 0)
        elif lib.periodo == 'Manhã':
            lib.hora_inicio = datetime.time(8, 0)
            lib.hora_fim = datetime.time(12, 0)
        elif lib.periodo == 'Tarde':
            lib.hora_inicio = datetime.time(14, 0)
            lib.hora_fim = datetime.time(18, 0)
        elif lib.periodo == 'Noturno':
            lib.hora_inicio = datetime.time(18, 0)
            lib.hora_fim = datetime.time(0, 0)
        else:
            lib.hora_inicio = datetime.time(8, 0)
            lib.hora_fim = datetime.time(18, 0)
        lib.save()

def backwards_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('equipe_tecnica', '0012_liberacaoacessodiaria_hora_fim_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
