# Generated by Django 5.2.8 on 2026-08-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipe_tecnica', '0013_data_migration_periodo_to_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liberacaoacessodiaria',
            name='periodo',
        ),
    ]
