# Generated by Django 5.2.8 on 2026-08-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe_tecnica', '0014_remove_liberacaoacessodiaria_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='liberacaoacessodiaria',
            name='supervisor_local',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Supervisor Local / Contato Segurança'),
        ),
        migrations.AddField(
            model_name='solicitacaoacesso',
            name='servico_executar',
            field=models.TextField(blank=True, null=True, verbose_name='Serviço a ser executado'),
        ),
        migrations.AlterField(
            model_name='padraoemailliberacao',
            name='corpo',
            field=models.TextField(help_text='Variáveis permitidas: {empresa}, {solicitante}, {periodo}, {datas}, {tecnicos}, {servico}, {supervisor}', verbose_name='Corpo da Mensagem'),
        ),
    ]
