# Generated by Django 5.2.8 on 2026-08-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe_tecnica', '0015_liberacaoacessodiaria_supervisor_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liberacaoacessodiaria',
            name='email_falhou',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liberacaoacessodiaria',
            name='erro_envio',
            field=models.TextField(blank=True, null=True, verbose_name='Log de Erro do Envio'),
        ),
    ]
