# Generated by Django 6.0 on 2026-07-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='dados',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
