# Generated by Django 6.0 on 2026-07-06 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentoAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Equipamento (Ex: Microfone Sem Fio Shure)', max_length=200)),
                ('categoria', models.CharField(choices=[('microfone', 'Microfone'), ('mesa_som', 'Mesa de Som'), ('caixa_som', 'Caixa de Som'), ('projetor', 'Projetor'), ('cabo', 'Cabo / Conector'), ('diversos', 'Diversos')], default='diversos', max_length=50)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('patrimonio', models.CharField(blank=True, help_text='Número de Patrimônio do TSE', max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('alocado', 'Alocado em Evento'), ('manutencao', 'Em Manutenção'), ('inativo', 'Inativo / Desativado')], default='disponivel', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventoAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome/Título do Evento', max_length=200)),
                ('solicitante', models.CharField(help_text='Área ou pessoa solicitante', max_length=200)),
                ('local', models.CharField(help_text='Local onde será o evento (Ex: Plenário, Auditório I)', max_length=200)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('descricao', models.TextField(blank=True, help_text='Descrição das necessidades de Áudio e Vídeo', null=True)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='agendado', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('equipamentos_alocados', models.ManyToManyField(blank=True, help_text='Equipamentos reservados para este evento', related_name='eventos_alocados', to='audiovideo.equipamentoav')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServicoAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(blank=True, help_text='Protocolo SEI ou Chamado', max_length=50, null=True)),
                ('defeito_relatado', models.TextField(help_text='Descrição do problema pelo usuário')),
                ('servico_realizado', models.TextField(blank=True, help_text='O que foi feito para consertar (Preenchido ao concluir)', null=True)),
                ('tecnico', models.CharField(blank=True, help_text='Técnico responsável pelo reparo', max_length=100, null=True)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('andamento', 'Em Atendimento'), ('concluida', 'Concluída')], default='aberta', max_length=20)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='audiovideo.equipamentoav')),
            ],
        ),
    ]
