# Generated by Django 6.0 on 2026-07-08 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiovideo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='Marca da TV', max_length=100)),
                ('modelo', models.CharField(help_text='Modelo da TV', max_length=100)),
                ('tamanho_polegadas', models.IntegerField(help_text='Tamanho em polegadas (ex: 55)')),
                ('patrimonio', models.CharField(help_text='Número de Patrimônio do TSE', max_length=50, unique=True)),
                ('protocolo_sei', models.CharField(blank=True, help_text='Protocolo SEI do pedido', max_length=50, null=True)),
                ('localizacao_atual', models.CharField(blank=True, help_text='Local onde a TV está atualmente', max_length=200, null=True)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('alocado', 'Alocado em Evento'), ('manutencao', 'Em Manutenção'), ('inativo', 'Inativo / Desativado')], default='disponivel', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='equipamentoav',
            name='sala_local',
            field=models.CharField(blank=True, help_text='Sala ou Local de Armazenamento/Instalação', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='equipamentoav',
            name='tipo_instalacao',
            field=models.CharField(choices=[('fixo', 'Instalação Fixa'), ('eventos', 'Uso em Eventos')], default='eventos', max_length=20),
        ),
        migrations.AddField(
            model_name='eventoav',
            name='relatorio_conclusao',
            field=models.TextField(blank=True, help_text='Relatório redigido pelo técnico/supervisor ao concluir o evento', null=True),
        ),
        migrations.AlterField(
            model_name='equipamentoav',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TransferenciaTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(help_text='Local de origem', max_length=200)),
                ('destino', models.CharField(help_text='Local de destino', max_length=200)),
                ('data_transferencia', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.CharField(help_text='Pessoa/Técnico responsável pela transferência', max_length=150)),
                ('motivo', models.TextField(blank=True, help_text='Motivo da transferência', null=True)),
                ('tv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='audiovideo.tv')),
            ],
        ),
    ]
