# Generated by Django 6.0 on 2026-07-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiovideo', '0002_tv_equipamentoav_sala_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamentoav',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor do item (R$)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tv',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor do item (R$)', max_digits=10, null=True),
        ),
    ]
