# Generated by Django 6.0 on 2026-03-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=13)),
                ('role', models.CharField(default='Geral', max_length=100)),
                ('is_ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_message', models.CharField(max_length=100, unique=True, verbose_name='Identificador do Template')),
                ('base_text', models.TextField(default='Prezado(a), {nome}\n\nSeguem as informações sobre a abertura do chamado para a empresa Otis:\n\nAtendente OTIS: {atendente}\nData/Hora: {data_hora}\nElevador: {elevador}\nOcorrência: {ocorrencia}\nProtocolo: {protocolo}\nSolicitante: {solicitante}')),
                ('is_ativo', models.BooleanField(default=True, verbose_name='Template Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contatos', models.ManyToManyField(blank=True, related_name='regras_notificacao', to='notificacoes.contato')),
            ],
        ),
    ]
