# Generated by Django 6.0 on 2026-04-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatemessage',
            old_name='id_message',
            new_name='id_template',
        ),
    ]
