# Generated by Django 6.0 on 2026-04-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0002_rename_id_message_templatemessage_id_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemessage',
            name='tipo_evento',
            field=models.CharField(choices=[('os_elev_registro', 'Elevadores - Registro de Nova OS'), ('os_elev_conclusao', 'Elevadores - Conclusão de OS Aberta')], default='false', max_length=80, unique=True, verbose_name='Gatilho / Situação'),
            preserve_default=False,
        ),
    ]
