# Generated by Django 6.0 on 2026-04-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0003_templatemessage_tipo_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemessage',
            name='tipo_evento',
            field=models.CharField(choices=[('false', '---'), ('os_elev_registro', 'Elevadores - Registro de Nova OS'), ('os_elev_conclusao', 'Elevadores - Conclusão de OS Aberta')], max_length=80, unique=True, verbose_name='Gatilho / Situação'),
        ),
    ]
