# Generated by Django 6.0 on 2026-07-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0005_alter_templatemessage_tipo_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemessage',
            name='tipo_evento',
            field=models.CharField(choices=[('false', '---'), ('os_elev_registro', 'Elevadores - Registro de Nova OS'), ('os_elev_conclusao', 'Elevadores - Conclusão de OS Aberta'), ('tel_solicitacao_aparelho', 'Telefonia - Solicitação de Aparelho'), ('tel_solicitacao_senha', 'Telefonia - Solicitação de Senha'), ('VAGO_1', 'Elevadores - TEMPLATE VAGO - 1'), ('VAGO_2', 'Elevadores - TEMPLATE VAGO - 2'), ('VAGO_3', 'Elevadores - TEMPLATE VAGO - 3'), ('VAGO_4', 'Elevadores - TEMPLATE VAGO - 4'), ('VAGO_5', 'Elevadores - TEMPLATE VAGO - 5'), ('VAGO_6', 'Elevadores - TEMPLATE VAGO - 6')], max_length=80, unique=True, verbose_name='Gatilho / Situação'),
        ),
    ]
