# Generated by Django 5.2.8 on 2026-07-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0008_alter_contato_id_alter_templatemessage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='templatemessage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='templatemessage',
            name='tipo_evento',
            field=models.CharField(choices=[('false', '---'), ('os_elev_registro', 'Elevadores - Registro de Nova OS'), ('os_elev_conclusao', 'Elevadores - Conclusão de OS Aberta'), ('tel_solicitacao_aparelho', 'Telefonia - Solicitação de Aparelho'), ('tel_solicitacao_senha', 'Telefonia - Solicitação de Senha'), ('os_elev_andamento', 'Elevadores - OS em Andamento'), ('VAGO_2', 'Elevadores - TEMPLATE VAGO - 2'), ('VAGO_3', 'Elevadores - TEMPLATE VAGO - 3'), ('VAGO_4', 'Elevadores - TEMPLATE VAGO - 4'), ('VAGO_5', 'Elevadores - TEMPLATE VAGO - 5'), ('VAGO_6', 'Elevadores - TEMPLATE VAGO - 6')], max_length=80, unique=True, verbose_name='Gatilho / Situação'),
        ),
    ]
