# Generated by Django 5.2.8 on 2026-07-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0010_alter_contato_id_alter_templatemessage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemessage',
            name='tipo_evento',
            field=models.CharField(choices=[('false', '---'), ('os_elev_registro', 'Elevadores - Registro de Nova OS'), ('os_elev_conclusao', 'Elevadores - Conclusão de OS Aberta'), ('tel_solicitacao_aparelho', 'Telefonia - Solicitação de Aparelho'), ('tel_solicitacao_senha', 'Telefonia - Solicitação de Senha'), ('os_elev_andamento', 'Elevadores - OS em Andamento'), ('os_elev_conclusao_peca', 'Elevadores - Conclusão de OS c/ Troca de Peça'), ('os_elev_aguardando_peca_parado', 'Elevadores - OS Aguardando Peça (Elev. Parado)'), ('os_elev_aguardando_peca_ativo', 'Elevadores - OS Aguardando Peça (Elev. Funcionando)'), ('VAGO_5', 'Elevadores - TEMPLATE VAGO - 5'), ('VAGO_6', 'Elevadores - TEMPLATE VAGO - 6')], max_length=80, unique=True, verbose_name='Gatilho / Situação'),
        ),
    ]
