# Generated by Django 5.2.8 on 2026-07-28 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0011_alter_templatemessage_tipo_evento'),
        ('usuarios', '0011_pessoa_formacaoprofissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contatos_notificacao', to='usuarios.pessoa'),
        ),
    ]
