# Generated by Django 5.2.8 on 2026-07-28 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0012_contato_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='telefone',
        ),
    ]
