# Generated by Django 6.0 on 2026-07-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0013_remove_contato_nome_remove_contato_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='notifica_elevadores',
            field=models.BooleanField(default=True, verbose_name='Recebe de Elevadores'),
        ),
        migrations.AddField(
            model_name='contato',
            name='notifica_telefonia',
            field=models.BooleanField(default=False, verbose_name='Recebe de Telefonia'),
        ),
        migrations.AddField(
            model_name='contato',
            name='receber_email',
            field=models.BooleanField(default=False, verbose_name='Receber via E-mail'),
        ),
        migrations.AddField(
            model_name='contato',
            name='receber_whatsapp',
            field=models.BooleanField(default=True, verbose_name='Receber via WhatsApp'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='is_ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='role',
            field=models.CharField(default='Geral', max_length=100, verbose_name='Tipo de Contato'),
        ),
    ]
