# Generated by Django 6.0 on 2026-07-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='classificacao',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Classificação/Ramo'),
        ),
    ]
