# Generated by Django 5.2.8 on 2026-07-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_classificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatoempresa',
            name='cargo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cargo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Cargo/Função Principal'),
        ),
        migrations.AlterField(
            model_name='contatoempresa',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
