# Generated by Django 5.2.8 on 2026-07-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_alter_contatoempresa_id_alter_empresa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatoempresa',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
