# Generated by Django 5.2.8 on 2026-07-28 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_alter_contatoempresa_id_alter_empresa_id'),
        ('usuarios', '0011_pessoa_formacaoprofissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatoempresa',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contato_empresas', to='usuarios.pessoa'),
        ),
    ]
