# Generated by Django 5.2.8 on 2026-07-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_contatoempresa_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contatoempresa',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contatoempresa',
            name='nome_contato',
        ),
        migrations.RemoveField(
            model_name='contatoempresa',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='contatoempresa',
            name='whatsapp',
        ),
    ]
