# Generated by Django 6.0 on 2026-05-18 16:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100, null=True)),
                ('cnpj', models.CharField(max_length=50)),
                ('num_contrato', models.CharField(default='', max_length=20)),
                ('objeto', models.CharField(max_length=1000)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('inicio_vigencia', models.DateField()),
                ('termino_vigencia', models.DateField()),
                ('sei_processo', models.CharField(default='', max_length=50)),
                ('sei_dod', models.CharField(blank=True, default='', max_length=50)),
                ('sei_etp', models.CharField(default='', max_length=50)),
                ('sei_tr', models.CharField(default='', max_length=50)),
                ('sei_edital', models.CharField(default='', max_length=50)),
                ('sei_fiscais', models.CharField(default='', max_length=50)),
                ('status', models.CharField(blank=True, default='VIGENTE', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_At', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
