# Generated by Django 6.0 on 2026-01-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=50)),
                ('num_contrato', models.CharField(max_length=20)),
                ('objeto', models.CharField(max_length=1000)),
                ('valor', models.FloatField()),
                ('inicio_vigencia', models.DateTimeField()),
                ('termino_vigencia', models.DateTimeField()),
                ('sei_processo', models.CharField(max_length=50)),
                ('sei_dod', models.CharField(max_length=50)),
                ('sei_etp', models.CharField(max_length=50)),
                ('sei_tr', models.CharField(max_length=50)),
                ('sei_edital', models.CharField(max_length=50)),
                ('sei_fiscais', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
