# Generated by Django 6.0 on 2026-07-13 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('empresas', '0002_empresa_classificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='cnpj',
        ),
        migrations.AlterField(
            model_name='contratos',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='empresas.empresa'),
        ),
    ]
