# Generated by Django 6.0 on 2026-01-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratosVigentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100, null=True)),
                ('cnpj', models.CharField(max_length=50)),
                ('num_contrato', models.CharField(max_length=20, null=True)),
                ('objeto', models.CharField(max_length=1000)),
                ('valor', models.FloatField()),
                ('inicio_vigencia', models.DateTimeField()),
                ('termino_vigencia', models.DateTimeField()),
                ('sei_processo', models.CharField(max_length=50)),
                ('sei_dod', models.CharField(max_length=50)),
                ('sei_etp', models.CharField(max_length=50)),
                ('sei_tr', models.CharField(max_length=50)),
                ('sei_edital', models.CharField(max_length=50)),
                ('sei_fiscais', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_At', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contratos',
        ),
    ]
