# Generated by Django 5.2.8 on 2026-07-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_remove_contratos_cnpj_alter_contratos_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
