# Generated by Django 6.0 on 2026-02-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_contratosvigentes_delete_contratos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratosvigentes',
            name='inicio_vigencia',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contratosvigentes',
            name='termino_vigencia',
            field=models.DateField(),
        ),
    ]
