# Generated by Django 6.0 on 2026-03-25 16:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_alter_contratosvigentes_inicio_vigencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratosvigentes',
            name='sei_dod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratosvigentes',
            name='sei_edital',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratosvigentes',
            name='sei_etp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratosvigentes',
            name='sei_fiscais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratosvigentes',
            name='sei_processo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratosvigentes',
            name='sei_tr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratosvigentes',
            name='status',
            field=models.CharField(blank=True, default='VIGENTE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contratosvigentes',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
