# Generated by Django 6.0 on 2026-03-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_alter_contratosvigentes_sei_dod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratosvigentes',
            name='sei_dod',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contratosvigentes',
            name='sei_edital',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contratosvigentes',
            name='sei_etp',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contratosvigentes',
            name='sei_fiscais',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contratosvigentes',
            name='sei_processo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contratosvigentes',
            name='sei_tr',
            field=models.CharField(default='', max_length=50),
        ),
    ]
