# Generated by Django 5.2.8 on 2026-07-14 16:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_alter_contratos_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoLicitatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=50, unique=True)),
                ('fase', models.CharField(choices=[('PLANEJAMENTO', 'Planejamento'), ('SELECAO', 'Seleção de Fornecedor'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PLANEJAMENTO', max_length=20)),
                ('modalidade', models.CharField(blank=True, max_length=50, null=True)),
                ('oficializacao_demanda_data', models.DateField(blank=True, null=True)),
                ('status_etp', models.CharField(blank=True, max_length=30, null=True)),
                ('link_etp', models.CharField(blank=True, max_length=255, null=True)),
                ('status_tr', models.CharField(blank=True, max_length=30, null=True)),
                ('link_tr', models.CharField(blank=True, max_length=255, null=True)),
                ('status_edital', models.CharField(blank=True, max_length=30, null=True)),
                ('link_edital', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='contratos',
            name='fiscal_substituto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='fiscal_titular',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='gestor_substituto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='gestor_titular',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='valor_mensal_estimado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='sei_dod',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='sei_edital',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='sei_etp',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='sei_fiscais',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='sei_processo',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='sei_tr',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='MedicaoMensal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(max_length=10)),
                ('valor_medido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('data_medicao', models.DateField()),
                ('avaliador', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='contratos.contratos')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_glosa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_multa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(default='PENDENTE', max_length=20)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='contratos.medicaomensal')),
            ],
        ),
        migrations.AddField(
            model_name='contratos',
            name='processo_licitatorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='contratos.processolicitatorio'),
        ),
    ]
