# Generated by Django 5.2.8 on 2026-07-14 17:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_processolicitatorio_contratos_fiscal_substituto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processolicitatorio',
            name='data_prevista_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='esta_no_pac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='objeto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='servidor_responsavel',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='unidade_responsavel',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='valor_previsto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='processolicitatorio',
            name='fase',
            field=models.CharField(choices=[('PREVISTA', 'Prevista'), ('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADA', 'Finalizada'), ('SUSPENSA', 'Suspensa'), ('PLANEJAMENTO', 'Planejamento'), ('SELECAO', 'Seleção de Fornecedor'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PREVISTA', max_length=20),
        ),
        migrations.CreateModel(
            name='CronogramaContratacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_artefato', models.CharField(choices=[('ETP', 'Estudo Técnico Preliminar (ETP)'), ('TR', 'Termo de Referência (TR)'), ('PESQUISA', 'Pesquisa de Preços'), ('EDITAL', 'Edital'), ('JURIDICO', 'Parecer Jurídico'), ('OUTRO', 'Outro')], max_length=20)),
                ('prazo_entrega', models.DateField()),
                ('data_entrega_real', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contratacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas', to='contratos.processolicitatorio')),
            ],
        ),
        migrations.CreateModel(
            name='TramitacaoSEI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_atual', models.CharField(max_length=150)),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('prazo_retorno', models.DateField(blank=True, null=True)),
                ('unidade_ultima_assinatura', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramitacoes_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('contratacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramitacoes', to='contratos.processolicitatorio')),
            ],
        ),
    ]
