# Generated by Django 6.0 on 2026-03-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_alter_contratosvigentes_sei_dod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratosvigentes',
            name='num_contrato',
            field=models.CharField(default='', max_length=20),
        ),
    ]
