# Generated by Django 6.0 on 2026-03-25 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_alter_contratosvigentes_num_contrato'),
        ('service_orders', '0013_engservicereg_contrato_engservicereg_empresa_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContratosVigentes',
            new_name='Contratos',
        ),
    ]
