# Generated by Django 5.2.8 on 2026-07-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_processolicitatorio_data_prevista_conclusao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processolicitatorio',
            name='descricao_objeto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='justificativa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20),
        ),
        migrations.AddField(
            model_name='tramitacaosei',
            name='atribuido_a',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tramitacaosei',
            name='data_ultima_movimentacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tramitacaosei',
            name='depende_de_nos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tramitacaosei',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tramitacaosei',
            name='para_onde_foi',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
