# Generated by Django 6.0 on 2026-03-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_rename_contratosvigentes_contratos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='sei_dod',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
