# Generated by Django 5.2.8 on 2026-07-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_processolicitatorio_descricao_objeto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processolicitatorio',
            name='eleicoes_ano_corrente',
            field=models.BooleanField(default=False),
        ),
    ]
