# Generated by Django 5.2.8 on 2026-07-14 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_processolicitatorio_eleicoes_ano_corrente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramitacaosei',
            name='para_onde_foi',
        ),
    ]
