# Generated by Django 5.2.8 on 2026-07-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0009_remove_tramitacaosei_para_onde_foi'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='app_vinculado',
            field=models.CharField(blank=True, choices=[('ELEVADORES', 'App Elevadores'), ('TELEFONIA', 'App Telefonia'), ('AUDIOVIDEO', 'App Áudio e Vídeo'), ('GESTAO_PATRIMONIO', 'App Gestão de Patrimônio'), ('REEMBOLSOS', 'App Reembolsos'), ('OUTROS', 'Outros')], max_length=50, null=True, verbose_name='Módulo App Sesen Vinculado'),
        ),
    ]
