# Generated by Django 5.2.8 on 2026-07-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_contratos_app_vinculado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='app_vinculado',
            field=models.CharField(blank=True, help_text='Pode conter múltiplos valores separados por vírgula', max_length=255, null=True, verbose_name='Módulos App Sesen Vinculados'),
        ),
    ]
