# Generated by Django 5.2.8 on 2026-07-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0011_alter_contratos_app_vinculado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='app_vinculado',
        ),
        migrations.AddField(
            model_name='contratos',
            name='categoria',
            field=models.CharField(choices=[('MANUTENCAO_PREDIAL', 'Manutenção Predial'), ('ELEVADORES', 'Elevadores'), ('TELEFONIA', 'Telefonia'), ('AUDIOVIDEO', 'Áudio e Vídeo'), ('TELEFONISTAS', 'Telefonistas'), ('GESTAO_PATRIMONIO', 'Gestão de Patrimônio'), ('REEMBOLSOS', 'Reembolsos'), ('OUTROS', 'Outros')], default='OUTROS', max_length=50, verbose_name='Categoria do Contrato'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('ARQUITETURA', 'Arquitetura'), ('ELETRICA', 'Elétrica'), ('HIDRAULICA', 'Hidráulica'), ('CIVIL', 'Civil'), ('MARCENARIA', 'Marcenaria')], max_length=50, null=True, verbose_name='Subcategoria (Manutenção Predial)'),
        ),
    ]
