# Generated by Django 5.2.8 on 2026-07-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0012_remove_contratos_app_vinculado_contratos_categoria_and_more'),
    ]

    operations = [
        # RemoveFields were executed before failure, so we omit them here to resume smoothly

        # AddFields were also executed before the failure, so we omit them too

        migrations.RunSQL('UPDATE contratos_contratos SET categoria = "[]", subcategoria = "[]";'),
        migrations.AlterField(
            model_name='contratos',
            name='categoria',
            field=models.JSONField(blank=True, default=list, verbose_name='Categoria do Contrato'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='subcategoria',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Subcategoria (Manutenção Predial)'),
        ),
    ]
