# Generated by Django 5.2.8 on 2026-07-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0013_remove_contratos_fiscal_substituto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='fiscal_substituto',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='fiscal_titular',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='gestor_substituto',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='gestor_titular',
        ),
        migrations.AddField(
            model_name='contratos',
            name='fiscal_admin_substituto',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fiscal Adm Substituto'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='fiscal_admin_titular',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fiscal Administrativo Titular'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='fiscal_tecnico_substituto',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fiscal Técnico Substituto'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='fiscal_tecnico_titular',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fiscal Técnico Titular'),
        ),
    ]
