# Generated by Django 5.2.8 on 2026-07-27 16:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0015_alter_contratos_id_alter_cronogramacontratacao_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaomensal',
            name='tipo_faturamento',
            field=models.CharField(choices=[('MENSAL', 'Mensal'), ('REEMBOLSO', 'Material/Serviço por Reembolso')], default='MENSAL', max_length=20),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='porcentagem_glosa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='porcentagem_multa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='protocolo_imr',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='protocolo_nf',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='protocolo_nota_tecnica',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='protocolo_relatorio_mensal',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='protocolo_trd_trt',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='valor_faturado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
