# Generated by Django 5.2.8 on 2026-07-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0016_medicaomensal_tipo_faturamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='ordem_pagamento',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
