# Generated by Django 5.2.8 on 2026-07-27 20:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0017_pagamento_ordem_pagamento'),
        ('equipe_tecnica', '0007_alter_liberacaoacessodiaria_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='contempla_postos_trabalho',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ItemCustoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Custo (Ex: Equipamentos, BDI)')),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos_extras', to='contratos.contratos')),
            ],
        ),
        migrations.CreateModel(
            name='PostoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(max_length=150, verbose_name='Posto de Trabalho (Cargo)')),
                ('tipo', models.CharField(choices=[('MENSALISTA', 'Mensalista'), ('PLANTONISTA', 'Plantonista')], default='MENSALISTA', max_length=20)),
                ('carga_horaria', models.CharField(blank=True, max_length=50, null=True, verbose_name='Carga Horária (Ex: 44h)')),
                ('quantidade_exigida', models.IntegerField(default=1, verbose_name='Quantidade de Postos Exigida')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postos_trabalho', to='contratos.contratos')),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tecnico_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profissional_contrato', to='equipe_tecnica.tecnico')),
            ],
        ),
        migrations.CreateModel(
            name='AlocacaoProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início na Alocação')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim (se inativo)')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='contratos.postotrabalho')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='contratos.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='TermoAditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Ex: 1/2026', max_length=50, verbose_name='Número do Aditivo')),
                ('objeto', models.TextField(blank=True, null=True, verbose_name='Objeto da Repactuação')),
                ('valor_aditivado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor Aditivado (+ ou -)')),
                ('novo_valor_global', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Novo Valor Global')),
                ('inicio_vigencia', models.DateField(verbose_name='Início da Vigência')),
                ('termino_vigencia', models.DateField(verbose_name='Término da Vigência')),
                ('necessita_novo_termo', models.BooleanField(default=False, verbose_name='Necessita Novo Termo Aditivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos_aditivos', to='contratos.contratos')),
            ],
        ),
    ]
