# Generated by Django 5.2.8 on 2026-07-27 21:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0018_contratos_contempla_postos_trabalho_itemcustoextra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postotrabalho',
            name='hora_extra_100',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Hora Extra 100%'),
        ),
        migrations.AddField(
            model_name='postotrabalho',
            name='hora_extra_50',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Hora Extra 50%'),
        ),
        migrations.AddField(
            model_name='postotrabalho',
            name='salario_bruto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Salário Bruto'),
        ),
        migrations.AddField(
            model_name='postotrabalho',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor da Hora'),
        ),
        migrations.AlterField(
            model_name='postotrabalho',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor Unitário para Empresa (Custo Total)'),
        ),
    ]
