# Generated by Django 5.2.8 on 2026-07-28 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0019_postotrabalho_hora_extra_100_and_more'),
        ('usuarios', '0011_pessoa_formacaoprofissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='pessoa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profissional', to='usuarios.pessoa'),
        ),
    ]
