# Generated by Django 5.2.8 on 2026-07-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0020_profissional_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='telefone',
        ),
    ]
