# Generated by Django 6.0 on 2026-07-29 18:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0021_remove_profissional_cpf_remove_profissional_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaEmpenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ne', models.CharField(max_length=50, verbose_name='Número da Nota de Empenho (Ex: 2026NE000123)')),
                ('valor_original', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_atual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor atualizado após possíveis anulações ou reforços', max_digits=12)),
                ('valor_anulado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('ANULADO_PARCIALMENTE', 'Anulado Parcialmente'), ('ANULADO_TOTALMENTE', 'Anulado Totalmente')], default='ATIVO', max_length=30)),
                ('atualizado_via_api', models.BooleanField(default=False, help_text='Indica se os dados vieram do SIAFI')),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_empenho', to='contratos.contratos')),
            ],
        ),
    ]
