# Generated by Django 6.0 on 2026-07-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0022_notaempenho'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='dia_limite_pagamento',
            field=models.IntegerField(default=10, help_text='Dia limite no mês subsequente para liquidação/pagamento'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='dias_para_atesto',
            field=models.IntegerField(default=5, help_text='Prazo em dias para atesto da NF após a medição'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='data_conclusao_atesto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='data_conclusao_liquidacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='data_conclusao_medicao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='fase_atual',
            field=models.CharField(choices=[('MEDICAO', 'Fase 1: Medição'), ('ATESTO', 'Fase 2: Atesto'), ('LIQUIDACAO', 'Fase 3: Liquidação'), ('PAGAMENTO', 'Fase 4: Pagamento (OB)'), ('CONCLUIDO', 'Concluído')], default='MEDICAO', max_length=20),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='protocolo_nota_liquidacao',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='protocolo_nota_sistema',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='protocolo_ordem_bancaria',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
